# BPClassifier — Boilerplate vs. Substantive Sentence Classifier

End-to-end pipeline for the BPClassifier course assignment.

**Pipeline steps**
1. Sentence extraction from earnings-call transcripts
2. Multi-judge gold labeling (Sonnet × 2 personas + Haiku) with disagreement audit
3. Stratified 60 / 20 / 20 split (frozen test)
4. Feature engineering: ~30 regex flags + frozen sentence embeddings
5. Classifier zoo: 12 entries across 7 families
6. 5-fold OOF threshold tuning under substantive recall ≥ 0.96
7. Held-out test evaluation and leaderboard
8. Save winning bundle for the GUI

**Alignment with the four focus items in the handout**

| Focus item | Where it lives in this notebook |
|---|---|
| Gold quality | §2 (three judges with distinct rubrics) and §3 (stratified disagreement audit) |
| Substantive recall ≥ 0.96 | §7 (OOF threshold sweep with hard floor; failures flagged, not relaxed) |
| Leaderboard breadth | §6 (12 entries, same features and splits, time + sent/sec reported) |
| GUI-ready model | §9 (joblib bundle: model + threshold + feature pipeline) |

**Re-runnable.** Every expensive step caches to Parquet (sentences, judge votes, embeddings) or joblib (models). Interrupt and re-run safely.

## 0 · Setup

Install dependencies if needed (uncomment the cell below). The pinned versions in `requirements.txt` are what this notebook was tested against.

In [1]:
# !pip install -q -r requirements.txt
# import nltk; nltk.download('punkt_tab', quiet=True); nltk.download('punkt', quiet=True)

In [45]:
from __future__ import annotations

import hashlib
import json
import os
import random
import re
import time
import warnings
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

import joblib
import numpy as np
import pandas as pd
import requests
from tqdm.auto import tqdm

warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning, module=r"sentence_transformers\.cross_encoder.*")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("WANDB_DISABLED", "true")

# --- Paths -----------------------------------------------------------------
PROJECT_ROOT = Path(".").resolve()
TRANSCRIPTS_DIR = PROJECT_ROOT / "transcripts"            # <-- DROP YOUR .txt FILES HERE
CACHE_DIR       = PROJECT_ROOT / "cache"
MODELS_DIR      = PROJECT_ROOT / "models"
REPORTS_DIR     = PROJECT_ROOT / "reports"
for d in (CACHE_DIR, MODELS_DIR, REPORTS_DIR):
    d.mkdir(exist_ok=True, parents=True)

# --- Reproducibility -------------------------------------------------------
SEED = 42
random.seed(SEED); np.random.seed(SEED)

# --- Pipeline knobs --------------------------------------------------------
GOLD_POOL_SIZE         = 2000          # how many sentences to send to the LLM judges (expanded from 1500)
MIN_SENT_CHARS         = 40            # drop fragments shorter than this
RECALL_FLOOR           = 0.96          # hard floor for substantive recall
EMBED_MODEL_NAME       = "sentence-transformers/all-mpnet-base-v2"
ENABLE_SETFIT          = True    # run SetFit strong-model pass
ENABLE_FINBERT         = False   # keep off for now; CPU-heavy overnight path
N_FOLDS                = 5
PARALLEL_JUDGE_WORKERS = 6             # be polite with the API

# --- Judge providers -------------------------------------------------------
# Set these in your shell before launching Jupyter, or paste them when prompted below.
os.environ.setdefault("ANTHROPIC_API_KEY", "PASTE_YOUR_ANTHROPIC_KEY_HERE")
os.environ.setdefault("OPENAI_API_KEY", "PASTE_YOUR_OPENAI_KEY_HERE")

JUDGE_MODELS = {
    "sonnet_balanced":   "claude-sonnet-4-6",
    "sonnet_skeptic":    "claude-sonnet-4-6",
    "haiku_pattern":     "claude-haiku-4-5",
    "gpt_mini_balanced": "gpt-4.1-mini",
}
JUDGE_PROVIDERS = {
    "sonnet_balanced":   "anthropic",
    "sonnet_skeptic":    "anthropic",
    "haiku_pattern":     "anthropic",
    "gpt_mini_balanced": "openai",
}

print("Project root:", PROJECT_ROOT)
print("Transcripts dir exists:", TRANSCRIPTS_DIR.exists(),
      f"({len(list(TRANSCRIPTS_DIR.glob('*.txt'))) if TRANSCRIPTS_DIR.exists() else 0} files)")
print("Judges:", {k: f"{JUDGE_PROVIDERS[k]}:{v}" for k, v in JUDGE_MODELS.items()})

Project root: /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2
Transcripts dir exists: True (131 files)
Judges: {'sonnet_balanced': 'anthropic:claude-sonnet-4-6', 'sonnet_skeptic': 'anthropic:claude-sonnet-4-6', 'haiku_pattern': 'anthropic:claude-haiku-4-5', 'gpt_mini_balanced': 'openai:gpt-4.1-mini'}

## 1 · Sentence extraction

Read every `.txt` transcript, split paragraphs, sentence-tokenize with NLTK punkt, dedupe, and drop short fragments. Saves to Parquet so we never repeat the work.

In [2]:
import nltk
try:
    nltk.data.find("tokenizers/punkt_tab")
except LookupError:
    nltk.download("punkt_tab", quiet=True)
    nltk.download("punkt", quiet=True)

from nltk.tokenize import sent_tokenize


def extract_sentences(transcripts_dir: Path, min_chars: int = MIN_SENT_CHARS) -> pd.DataFrame:
    rows = []
    for fp in sorted(transcripts_dir.glob("*.txt")):
        text = fp.read_text(encoding="utf-8", errors="ignore")
        # Paragraph split first (preserves speaker turns better than naive tokenization)
        for para in (p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()):
            for sent in sent_tokenize(para):
                sent = re.sub(r"\s+", " ", sent).strip()
                if len(sent) < min_chars:
                    continue
                rows.append({
                    "transcript": fp.stem,
                    "sentence": sent,
                    "char_len": len(sent),
                })

    df = pd.DataFrame(rows).drop_duplicates(subset=["sentence"]).reset_index(drop=True)
    df["sentence_id"] = df["sentence"].apply(
        lambda s: hashlib.md5(s.encode("utf-8")).hexdigest()[:12]
    )
    return df[["sentence_id", "transcript", "sentence", "char_len"]]


SENTENCES_PARQUET = CACHE_DIR / "sentences.parquet"

if SENTENCES_PARQUET.exists():
    sentences_df = pd.read_parquet(SENTENCES_PARQUET)
    print(f"Loaded {len(sentences_df):,} sentences from cache.")
else:
    assert TRANSCRIPTS_DIR.exists(), f"Place .txt transcripts in {TRANSCRIPTS_DIR}"
    sentences_df = extract_sentences(TRANSCRIPTS_DIR)
    sentences_df.to_parquet(SENTENCES_PARQUET, index=False)
    print(f"Extracted {len(sentences_df):,} sentences from "
          f"{sentences_df['transcript'].nunique()} transcripts.")

sentences_df.head(5)

Loaded 55,636 sentences from cache.

,sentence_id,transcript,sentence,char_len
0,4bbc8d818ab7,AMD_Q1-2024,"﻿Advanced Micro Devices, Inc., Q1 2024 Earning...",68
1,68f96bc4d200,AMD_Q1-2024,Presentation Operator Message Operator Greetin...,108
2,68635a3ee46e,AMD_Q1-2024,"[Operator Instructions] As a reminder, this co...",73
3,654a46e7cada,AMD_Q1-2024,"It is now my pleasure to introduce your host, ...",93
4,4b772535d61e,AMD_Q1-2024,Presenter Speech Executives - Former Vice Pres...,159

## 2 · Gold labeling — four judges, mixed providers

Per the handout, label quality is the single biggest credibility lever. We use **four distinct judges** and majority-vote, with one judge coming from a different provider family to reduce correlated mistakes on borderline sentences.

| Judge | Provider | Model | Persona |
|---|---|---|---|
| `sonnet_balanced` | Anthropic | claude-sonnet-4-6 | Balanced reviewer following the rubric strictly |
| `sonnet_skeptic`  | Anthropic | claude-sonnet-4-6 | Materiality skeptic — defaults to boilerplate when the sentence carries no specific information a downstream analyst would keep |
| `haiku_pattern`   | Anthropic | claude-haiku-4-5  | Fast pattern-detector — focuses on lexical cues |
| `gpt_mini_balanced` | OpenAI | gpt-4.1-mini | Cheap cross-provider balanced reviewer for decorrelated edge-case votes |

This gives us two provider families and four rubric/model perspectives. Each judge returns strict JSON with a label, a 0–1 confidence, and a one-line rationale. All outputs are cached per `(sentence_id, judge)` so you can interrupt and resume.

**Why add GPT mini?**
- It is cheap enough to use on the gold pool.
- It gives us a cross-provider opinion on borderline rows.
- It reduces the chance that all judges repeat the same Anthropic-style mistake.

**Cost & resilience features built in:**
- **Prompt caching** still applies to the Anthropic judges on the long repeated rubric.
- **Disk flush every 25 votes** — if the kernel dies you lose at most 25 calls.
- **Insufficient-balance detection** — if one provider runs out of credits mid-run, the loop exits cleanly with a clear message.
- **Hot-swap helpers** for both Anthropic and OpenAI keys without restarting the kernel.
- **Ctrl-C safe** — flushes pending votes before exiting.

In [172]:
# ---- Sample the gold pool ------------------------------------------------
GOLD_POOL_PARQUET = CACHE_DIR / "gold_pool.parquet"

if GOLD_POOL_PARQUET.exists():
    gold_pool = pd.read_parquet(GOLD_POOL_PARQUET)
    print(f"Loaded gold pool of {len(gold_pool):,} sentences from cache.")
else:
    # Stratify across transcripts so no single call dominates the gold set.
    rng = np.random.default_rng(SEED)
    per_transcript = max(1, GOLD_POOL_SIZE // max(1, sentences_df["transcript"].nunique()))
    sampled = (
        sentences_df.groupby("transcript", group_keys=False)
                    .apply(lambda g: g.sample(min(len(g), per_transcript), random_state=SEED))
    )
    if len(sampled) > GOLD_POOL_SIZE:
        sampled = sampled.sample(GOLD_POOL_SIZE, random_state=SEED)
    elif len(sampled) < GOLD_POOL_SIZE:
        # top up from the remainder
        remainder = sentences_df.drop(sampled.index)
        topup = remainder.sample(min(GOLD_POOL_SIZE - len(sampled), len(remainder)),
                                 random_state=SEED)
        sampled = pd.concat([sampled, topup])
    gold_pool = sampled.reset_index(drop=True)
    gold_pool.to_parquet(GOLD_POOL_PARQUET, index=False)
    print(f"Sampled {len(gold_pool):,} sentences for gold labeling.")

gold_pool.head(3)

Loaded gold pool of 2,000 sentences from cache.

,sentence_id,transcript,sentence,char_len
0,a5c9476fbedc,AMD_Q1-2024,"As I said, we have great customer engagements ...",69
1,cd7521ab9a17,AMD_Q1-2024,"Looking further ahead, AI represents an unprec...",74
2,e6a7bb29a86c,AMD_Q1-2024,"So overall, will help the mix on the gross mar...",55

In [5]:
# ---- EXPANSION: Move from 1500 to 2000 gold labels ----
# This adds 500 new sentences for labeling
# Cost: ~$5-6 additional (with prompt caching)
# Expected F1 gain: +0.02-0.03 (from 0.7603 to 0.78-0.79)

print("="*100)
print("SCALING UP: 1500 → 2000 sentences")
print("="*100)

# Update the variable
GOLD_POOL_SIZE = 2000
print(f"ℹ️  Updated GOLD_POOL_SIZE to {GOLD_POOL_SIZE:,}")

# Clear the cached gold pool to force resampling 2000
gold_pool_cache = CACHE_DIR / "gold_pool.parquet"
if gold_pool_cache.exists():
    gold_pool_cache.unlink()
    print(f"✅ Cleared gold pool cache.")

# Resample now with new size
rng = np.random.default_rng(SEED)
per_transcript = max(1, GOLD_POOL_SIZE // max(1, sentences_df["transcript"].nunique()))
sampled = (
    sentences_df.groupby("transcript", group_keys=False)
                .apply(lambda g: g.sample(min(len(g), per_transcript), random_state=SEED))
)
if len(sampled) > GOLD_POOL_SIZE:
    sampled = sampled.sample(GOLD_POOL_SIZE, random_state=SEED)
elif len(sampled) < GOLD_POOL_SIZE:
    remainder = sentences_df.drop(sampled.index)
    topup = remainder.sample(min(GOLD_POOL_SIZE - len(sampled), len(remainder)), random_state=SEED)
    sampled = pd.concat([sampled, topup])
gold_pool = sampled.reset_index(drop=True)
gold_pool.to_parquet(GOLD_POOL_PARQUET, index=False)

print(f"✅ Resampled {len(gold_pool):,} sentences for gold labeling.")
print(f"\nNext steps:")
print(f"1. Run Cell 11 (judge voting) → will label the ~500 new sentences")
print(f"2. Run Cell 12 (adjudication) → merge all votes (cached 1500 + new 500)")
print(f"3. Run audit on all 2000 → identify label errors")
print(f"4. Retrain models on expanded gold set")
print("="*100)

====================================================================================================
SCALING UP: 1500 → 2000 sentences
====================================================================================================
ℹ️  Updated GOLD_POOL_SIZE to 2,000
✅ Cleared gold pool cache.
✅ Resampled 2,000 sentences for gold labeling.

Next steps:
1. Run Cell 11 (judge voting) → will label the ~500 new sentences
2. Run Cell 12 (adjudication) → merge all votes (cached 1500 + new 500)
3. Run audit on all 2000 → identify label errors
4. Retrain models on expanded gold set
====================================================================================================

In [46]:
# ---- Rubrics with anchor examples ---------------------------------------
RUBRIC_DEFINITIONS = """\
TASK
You are labeling a single sentence from an earnings-call transcript as one of two classes.

CLASSES
- "boilerplate": scripted intros, safe-harbor / forward-looking-statement language,
  operator and analyst housekeeping, generic thanks, name introductions, transitions,
  one-word fillers in Q&A, vague pleasantries with no material information.
- "substantive": material numbers, guidance, segment commentary, strategy, specific
  Q&A answers (even short ones if they carry a specific fact, number, or commitment).

ANCHOR EXAMPLES - boilerplate
- "Good afternoon and welcome to the third quarter 2024 earnings conference call."
- "All lines have been placed on mute to prevent any background noise."
- "Today's discussion may include forward-looking statements within the meaning of the Private Securities Litigation Reform Act."
- "Hi, this is Sarah from Goldman Sachs."
- "Thanks for taking my question."
- "I'd add that we're encouraged by the trends." (no specifics)
- "Let me turn the call over to our CFO."
- "That concludes today's call. Thank you for joining."

ANCHOR EXAMPLES - substantive
- "Revenue grew 14% year-over-year to $2.3 billion, driven by strength in our cloud segment."
- "We are raising our full-year EPS guidance to a range of $4.20 to $4.30."
- "Operating margin contracted 80 basis points due to higher input costs."
- "We expect mid-single-digit growth in our consumer business next quarter."
- "We repurchased $500 million of stock during the quarter."
- "We saw strength across all three verticals." (segment commentary even if vague)

EDGE CASES
- One-word answers ("Yes.", "Sure.") with no following content -> boilerplate.
- Mixed sentences ("Hi John, thanks - to your point, margins compressed 60 bps.") ->
  substantive (any material content tips it substantive).
- Hedging without numbers ("We feel good about the trajectory.") -> boilerplate.
- Generic strategy with no specifics ("We continue to invest in innovation.") -> boilerplate.

OUTPUT FORMAT
Return ONLY a single JSON object on one line, no prose, no markdown fences:
{"label": "boilerplate"|"substantive", "confidence": 0.0-1.0, "rationale": "<=15 words"}
"""

# Prompt caching only takes effect above Anthropic's minimum cacheable prompt size.
# These repeated calibration examples are static, so they are cheap after cache warm-up.
_CACHE_PADDING_EXAMPLES = [
    'Boilerplate: "Operator, please open the line for questions." - call logistics only.',
    'Boilerplate: "Thank you, everyone, for joining us today." - closing thanks only.',
    'Boilerplate: "Please note that our remarks contain forward-looking statements." - safe harbor.',
    'Boilerplate: "This is Mark from JPMorgan." - speaker introduction only.',
    'Boilerplate: "We appreciate the question and the continued support." - pleasantry only.',
    'Substantive: "Data center revenue increased 80% year over year to $2.3 billion." - metric plus segment.',
    'Substantive: "We expect gross margin to improve by roughly 50 basis points next quarter." - guidance.',
    'Substantive: "Inventory declined by $120 million as sell-through improved." - financial detail.',
    'Substantive: "Enterprise demand was strongest in healthcare and financial services." - segment commentary.',
    'Substantive: "We signed three hyperscaler customers for the new accelerator platform." - concrete customer detail.',
    'Rule reminder: label the current sentence only, not surrounding transcript context.',
    'Rule reminder: any specific number, guidance range, named segment, or material causal explanation usually makes the sentence substantive.',
]
CACHE_PADDING = "\n".join(
    f"CALIBRATION {rep + 1:02d}.{i + 1:02d}: {example}"
    for rep in range(10)
    for i, example in enumerate(_CACHE_PADDING_EXAMPLES)
)

RUBRIC_BALANCED = RUBRIC_DEFINITIONS + """
You are the BALANCED REVIEWER. Apply the rubric literally. When genuinely on the fence,
report confidence <= 0.55 and pick the class the rubric definitions favor.
""" + CACHE_PADDING

RUBRIC_SKEPTIC = RUBRIC_DEFINITIONS + """
You are the MATERIALITY SKEPTIC. Default to "boilerplate" unless the sentence carries
specific material information (numbers, guidance, named segments/products/strategy)
that a downstream financial analyst would actually want to keep. Vague optimism and
generic strategy talk are boilerplate.
""" + CACHE_PADDING

RUBRIC_PATTERN = RUBRIC_DEFINITIONS + """
You are the PATTERN DETECTOR. Be fast and consistent. Lexical cues like operator
phrases, safe-harbor language, analyst firm names, and generic thanks are strong
boilerplate signals. Numbers, percentages, dollar amounts, basis points, and explicit
guidance language are strong substantive signals.
""" + CACHE_PADDING

RUBRIC_GPT_MINI = RUBRIC_DEFINITIONS + """
You are a CROSS-PROVIDER BALANCED REVIEWER. Apply the rubric literally and resist
copying vague optimism into the substantive class unless the sentence contains a
specific number, business driver, named segment/product, or material causal claim.
When genuinely on the fence, report confidence <= 0.55.
"""

JUDGE_RUBRICS = {
    "sonnet_balanced": RUBRIC_BALANCED,
    "sonnet_skeptic":  RUBRIC_SKEPTIC,
    "haiku_pattern":   RUBRIC_PATTERN,
    "gpt_mini_balanced": RUBRIC_GPT_MINI,
}
print("Rubrics defined:", list(JUDGE_RUBRICS.keys()))
print("Approx rubric chars:", {k: len(v) for k, v in JUDGE_RUBRICS.items()})

Rubrics defined: ['sonnet_balanced', 'sonnet_skeptic', 'haiku_pattern', 'gpt_mini_balanced']
Approx rubric chars: {'sonnet_balanced': 16265, 'sonnet_skeptic': 16395, 'haiku_pattern': 16400, 'gpt_mini_balanced': 2465}

In [171]:
# ---- Active judge configuration: 3-way mix (OpenAI + Haiku + best Sonnet) ----
# Goal: reduce correlated errors while keeping annotation cost and runtime lower.

TARGET_MACRO_F1 = 0.80
TARGET_RECALL = 0.96
UPSIZE_GOLD_IF_NEEDED = 2500

votes_cache = CACHE_DIR / "judge_votes.parquet"
gold_cache = CACHE_DIR / "gold.parquet"

best_sonnet = "sonnet_balanced"  # fallback
if votes_cache.exists() and gold_cache.exists():
    try:
        v = pd.read_parquet(votes_cache)
        g = pd.read_parquet(gold_cache)[["sentence_id", "y"]].copy()
        g["sentence_id"] = g["sentence_id"].astype(str)

        sonnet_scores = {}
        for j in ["sonnet_balanced", "sonnet_skeptic"]:
            jj = v[v["judge"] == j][["sentence_id", "label"]].copy()
            if len(jj) == 0:
                continue
            jj["sentence_id"] = jj["sentence_id"].astype(str)
            m = jj.merge(g, on="sentence_id", how="inner")
            if len(m) < 100:
                continue
            y_true = m["y"].astype(int).values
            y_pred = (m["label"].values == "substantive").astype(int)
            sonnet_scores[j] = {
                "macro_f1_vs_gold": f1_score(y_true, y_pred, average="macro", zero_division=0),
                "n": len(m),
            }

        if sonnet_scores:
            best_sonnet = max(sonnet_scores, key=lambda k: sonnet_scores[k]["macro_f1_vs_gold"])
            print("Sonnet comparison vs current frozen gold:")
            print(pd.DataFrame(sonnet_scores).T.sort_values("macro_f1_vs_gold", ascending=False).round(4))
    except Exception as e:
        print(f"Judge selection fallback due to cache read/scoring issue: {e!r}")

ACTIVE_JUDGES = ["gpt_mini_balanced", "haiku_pattern", best_sonnet]

# Keep dictionaries in this exact order for reproducible pivots/columns.
JUDGE_MODELS = {j: JUDGE_MODELS[j] for j in ACTIVE_JUDGES}
JUDGE_PROVIDERS = {j: JUDGE_PROVIDERS[j] for j in ACTIVE_JUDGES}
JUDGE_RUBRICS = {j: JUDGE_RUBRICS[j] for j in ACTIVE_JUDGES}

print("Active 3-judge panel:", ACTIVE_JUDGES)
print("Targets:", {"macro_f1": f">{TARGET_MACRO_F1}", "sub_recall": f">={TARGET_RECALL}"})
print("Upsize trigger pool:", UPSIZE_GOLD_IF_NEEDED)

Sonnet comparison vs current frozen gold:
                 macro_f1_vs_gold       n
sonnet_skeptic             0.9319  2000.0
sonnet_balanced            0.8965  2000.0
Active 3-judge panel: ['gpt_mini_balanced', 'haiku_pattern', 'sonnet_skeptic']
Targets: {'macro_f1': '>0.8', 'sub_recall': '>=0.96'}
Upsize trigger pool: 2500

In [47]:
# ---- Multi-provider judge clients + per-sentence judge call --------------
# Anthropic judges use prompt caching; OpenAI adds a cheap cross-provider vote.
from anthropic import Anthropic

_anthropic_client = None


class InsufficientBalance(Exception):
    """A provider account is out of credits."""


class NoApiKey(Exception):
    """A required provider key is unset or still a placeholder."""


def _is_balance_error(err: Exception) -> bool:
    msg = (str(err) + " " + repr(err)).lower()
    return (
        "credit balance" in msg
        or "insufficient_balance" in msg
        or ("billing" in msg and "low" in msg)
        or "quota" in msg
    )


def _get_anthropic_client() -> Anthropic:
    global _anthropic_client
    if _anthropic_client is None:
        key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
        if not key or key == "PASTE_YOUR_ANTHROPIC_KEY_HERE" or not key.startswith("sk-ant-"):
            raise NoApiKey(
                "ANTHROPIC_API_KEY is not set. Set it via "
                "os.environ['ANTHROPIC_API_KEY'] = 'sk-ant-...' or use switch_api_key(..., provider='anthropic')."
            )
        _anthropic_client = Anthropic(api_key=key)
    return _anthropic_client


def _get_openai_key() -> str:
    key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not key or key == "PASTE_YOUR_OPENAI_KEY_HERE" or not key.startswith("sk-"):
        raise NoApiKey(
            "OPENAI_API_KEY is not set. Set it via "
            "os.environ['OPENAI_API_KEY'] = 'sk-...' or use switch_api_key(..., provider='openai')."
        )
    return key


def switch_api_key(new_key: str, provider: str = "anthropic") -> None:
    global _anthropic_client
    provider = provider.strip().lower()
    if provider == "anthropic":
        os.environ["ANTHROPIC_API_KEY"] = new_key.strip()
        _anthropic_client = None
    elif provider == "openai":
        os.environ["OPENAI_API_KEY"] = new_key.strip()
    else:
        raise ValueError(f"Unknown provider: {provider}")
    print(f"{provider} API key updated. The next API call will use the new key.")


_JSON_RE = re.compile(r"\{.*?\}", re.DOTALL)


def _parse_judge_json(raw: str) -> dict | None:
    raw = raw.strip()
    for candidate in (raw, *(_JSON_RE.findall(raw) or [])):
        try:
            obj = json.loads(candidate)
        except Exception:
            continue
        label = str(obj.get("label", "")).lower().strip()
        if label not in {"boilerplate", "substantive"}:
            continue
        try:
            conf = float(obj.get("confidence", 0.5))
        except Exception:
            conf = 0.5
        conf = max(0.0, min(1.0, conf))
        return {
            "label": label,
            "confidence": conf,
            "rationale": str(obj.get("rationale", ""))[:200],
        }
    return None


def _anthropic_usage(resp) -> dict:
    usage = getattr(resp, "usage", None)
    fields = [
        "input_tokens", "cache_creation_input_tokens", "cache_read_input_tokens",
        "output_tokens", "server_tool_use", "service_tier",
    ]
    return {f"usage_{name}": getattr(usage, name, None) for name in fields}


def _openai_usage(payload: dict) -> dict:
    usage = payload.get("usage", {}) or {}
    prompt_tokens = usage.get("prompt_tokens")
    completion_tokens = usage.get("completion_tokens")
    total_tokens = usage.get("total_tokens")
    return {
        "usage_input_tokens": prompt_tokens,
        "usage_cache_creation_input_tokens": None,
        "usage_cache_read_input_tokens": None,
        "usage_output_tokens": completion_tokens,
        "usage_server_tool_use": None,
        "usage_service_tier": payload.get("service_tier") or total_tokens,
    }


def _call_anthropic_judge(sentence: str, model_id: str, rubric: str) -> dict:
    resp = _get_anthropic_client().messages.create(
        model=model_id,
        max_tokens=120,
        temperature=0.0,
        system=[{"type": "text", "text": rubric,
                 "cache_control": {"type": "ephemeral"}}],
        messages=[{"role": "user", "content": f"SENTENCE:\n{sentence}\n\nReturn the JSON now."}],
    )
    text = "".join(b.text for b in resp.content if getattr(b, "type", "") == "text")
    parsed = _parse_judge_json(text)
    if parsed is None:
        raise ValueError(f"unparseable Anthropic response: {text[:120]!r}")
    parsed.update(_anthropic_usage(resp))
    return parsed


def _call_openai_judge(sentence: str, model_id: str, rubric: str) -> dict:
    payload = {
        "model": model_id,
        "temperature": 0.0,
        "max_completion_tokens": 120,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": rubric},
            {"role": "user", "content": f"SENTENCE:\n{sentence}\n\nReturn the JSON now."},
        ],
    }
    resp = requests.post(
        "https://api.openai.com/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {_get_openai_key()}",
            "Content-Type": "application/json",
        },
        json=payload,
        timeout=90,
    )
    if resp.status_code in {401, 403}:
        raise NoApiKey("OpenAI rejected the API key. Update OPENAI_API_KEY and retry.")
    if resp.status_code == 429:
        raise InsufficientBalance(resp.text)
    resp.raise_for_status()
    body = resp.json()
    text = body["choices"][0]["message"]["content"]
    parsed = _parse_judge_json(text)
    if parsed is None:
        raise ValueError(f"unparseable OpenAI response: {text[:120]!r}")
    parsed.update(_openai_usage(body))
    return parsed


def ensure_provider_keys(judges: list[str]) -> None:
    providers = {JUDGE_PROVIDERS[j] for j in judges}
    if "anthropic" in providers:
        _get_anthropic_client()
    if "openai" in providers:
        _get_openai_key()


def call_judge(sentence: str, judge_name: str, max_retries: int = 4) -> dict:
    provider = JUDGE_PROVIDERS[judge_name]
    model_id = JUDGE_MODELS[judge_name]
    rubric = JUDGE_RUBRICS[judge_name]

    last_err = None
    for attempt in range(max_retries):
        try:
            if provider == "anthropic":
                return _call_anthropic_judge(sentence, model_id, rubric)
            if provider == "openai":
                return _call_openai_judge(sentence, model_id, rubric)
            raise ValueError(f"Unsupported provider: {provider}")
        except NoApiKey:
            raise
        except Exception as e:
            if _is_balance_error(e):
                raise InsufficientBalance(str(e)) from e
            last_err = repr(e)
        time.sleep(1.5 * (2 ** attempt))

    return {
        "label": "boilerplate",
        "confidence": 0.5,
        "rationale": f"FAIL: {last_err}",
        "_error": True,
    }

In [48]:
# ---- API key prompt -----------------------------------------------------
# Paste provider keys when prompted. The input is hidden and is not saved
# into this notebook file.
from getpass import getpass

_anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
if not _anthropic_key.startswith("sk-ant-") or _anthropic_key == "PASTE_YOUR_ANTHROPIC_KEY_HERE":
    switch_api_key(getpass("Enter your Anthropic API key: "), provider="anthropic")
else:
    print("ANTHROPIC_API_KEY is already set for this kernel.")

_openai_key = os.environ.get("OPENAI_API_KEY", "").strip()
if not _openai_key.startswith("sk-") or _openai_key == "PASTE_YOUR_OPENAI_KEY_HERE":
    switch_api_key(getpass("Enter your OpenAI API key for GPT mini: "), provider="openai")
else:
    print("OPENAI_API_KEY is already set for this kernel.")

anthropic API key updated. The next API call will use the new key.
openai API key updated. The next API call will use the new key.

In [173]:
# ---- Run all judges with caching + parallelism --------------------------
JUDGE_VOTES_PARQUET = CACHE_DIR / "judge_votes.parquet"
FLUSH_EVERY = 25       # save to disk every N votes (was 100; lower = safer resume)
USAGE_COLS = [
    "usage_input_tokens", "usage_cache_creation_input_tokens",
    "usage_cache_read_input_tokens", "usage_output_tokens",
    "usage_server_tool_use", "usage_service_tier",
]
VOTE_COLS = ["sentence_id", "judge", "label", "confidence", "rationale", *USAGE_COLS]


def _clean_votes(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return pd.DataFrame(columns=VOTE_COLS)
    cleaned = df.copy()
    for col in VOTE_COLS:
        if col not in cleaned.columns:
            cleaned[col] = np.nan
    bad = (
        cleaned["rationale"].astype(str).str.startswith("FAIL:")
        | ~cleaned["label"].isin(["boilerplate", "substantive"])
        | cleaned[["sentence_id", "judge"]].isna().any(axis=1)
    )
    if bad.any():
        print(f"Dropping {bad.sum():,} bad cached vote rows before resume.")
    cleaned = cleaned.loc[~bad, VOTE_COLS]
    return cleaned.drop_duplicates(subset=["sentence_id", "judge"], keep="last")


def load_existing_votes() -> pd.DataFrame:
    if JUDGE_VOTES_PARQUET.exists():
        existing = _clean_votes(pd.read_parquet(JUDGE_VOTES_PARQUET))
        existing.to_parquet(JUDGE_VOTES_PARQUET, index=False)
        return existing
    return pd.DataFrame(columns=VOTE_COLS)


def _vote_row(sid: str, judge: str, res: dict) -> dict:
    row = {
        "sentence_id": sid, "judge": judge,
        "label": res["label"], "confidence": res["confidence"],
        "rationale": res.get("rationale", ""),
    }
    for col in USAGE_COLS:
        row[col] = res.get(col)
    return row


def label_pool(pool: pd.DataFrame, workers: int = PARALLEL_JUDGE_WORKERS) -> pd.DataFrame:
    existing = load_existing_votes()
    have = set(zip(existing["sentence_id"], existing["judge"]))

    todo = []
    for _, row in pool.iterrows():
        for judge in JUDGE_MODELS:
            if (row["sentence_id"], judge) not in have:
                todo.append((row["sentence_id"], row["sentence"], judge))

    if not todo:
        print("All judge votes are cached.")
        return existing

    try:
        ensure_provider_keys([j for _, _, j in todo])
    except NoApiKey as e:
        print(f"!! {e}")
        print("   No API calls were made. Set the missing key and re-run.")
        return existing

    print(f"Calling judges for {len(todo):,} (sentence, judge) pairs...")
    new_rows: list[dict] = []
    aborted = False

    # Warm each judge once. This still helps Anthropic caching and is harmless for OpenAI.
    warmup, remaining, warmed = [], [], set()
    for item in todo:
        judge = item[2]
        if judge not in warmed:
            warmup.append(item)
            warmed.add(judge)
        else:
            remaining.append(item)

    try:
        if warmup:
            print(f"Warming {len(warmup)} judge prefixes sequentially...")
            for sid, sentence, judge in warmup:
                res = call_judge(sentence, judge)
                new_rows.append(_vote_row(sid, judge, res))
            existing = _flush_votes(existing, new_rows)

        if remaining:
            with ThreadPoolExecutor(max_workers=workers) as ex:
                futures = {
                    ex.submit(call_judge, sentence, judge): (sid, judge)
                    for sid, sentence, judge in remaining
                }
                for fut in tqdm(as_completed(futures), total=len(futures)):
                    sid, judge = futures[fut]
                    try:
                        res = fut.result()
                    except InsufficientBalance as e:
                        print(f"\n!! Insufficient credits: {e}")
                        print("   Stopping cleanly. Cached votes so far are safe on disk.")
                        print("   Top up the provider account, then re-run this cell to resume.")
                        aborted = True
                        break
                    except NoApiKey as e:
                        print(f"\n!! {e}")
                        print("   Stopping. Set the missing provider key and re-run this cell.")
                        aborted = True
                        break
                    except Exception as e:
                        res = {"label": "boilerplate", "confidence": 0.5,
                               "rationale": f"FAIL: {e!r}", "_error": True}
                    new_rows.append(_vote_row(sid, judge, res))
                    if len(new_rows) % FLUSH_EVERY == 0:
                        existing = _flush_votes(existing, new_rows)
                if aborted:
                    for f in futures:
                        f.cancel()
    except KeyboardInterrupt:
        print("\n!! Interrupted. Flushing what we have...")
        aborted = True
    except (InsufficientBalance, NoApiKey) as e:
        print(f"\n!! {e}")
        aborted = True

    existing = _flush_votes(existing, new_rows)
    if aborted:
        print("Run stopped early; cached valid votes are preserved.")
    return existing


def _flush_votes(existing: pd.DataFrame, new_rows: list[dict]) -> pd.DataFrame:
    if not new_rows:
        return existing
    combined = pd.concat([existing, pd.DataFrame(new_rows)], ignore_index=True)
    combined = _clean_votes(combined)
    combined.to_parquet(JUDGE_VOTES_PARQUET, index=False)
    new_rows.clear()
    return combined


# --- Run the judges -------------------------------------------------------
# To swap to a different API key without restarting the kernel:
#   switch_api_key("...", provider="anthropic")
#   switch_api_key("...", provider="openai")
votes_df = label_pool(gold_pool)
print(f"Total valid votes on disk: {len(votes_df):,}")
usage_cols_present = [c for c in USAGE_COLS if c in votes_df]
if usage_cols_present and len(votes_df):
    print(votes_df.groupby("judge")[usage_cols_present].sum(numeric_only=True).round(0))
votes_df.head(6)

All judge votes are cached.
Total valid votes on disk: 8,171
                   usage_input_tokens  usage_cache_creation_input_tokens  \
judge
gpt_mini_balanced           1192477.0                                0.0
haiku_pattern                 89749.0                            34608.0
sonnet_balanced               89749.0                            47322.0
sonnet_skeptic                89749.0                            47586.0

                   usage_cache_read_input_tokens  usage_output_tokens
judge
gpt_mini_balanced                            0.0              65277.0
haiku_pattern                          8863974.0              89544.0
sonnet_balanced                        8801892.0              81637.0
sonnet_skeptic                         8850996.0              81708.0

,sentence_id,judge,label,confidence,rationale,usage_input_tokens,usage_cache_creation_input_tokens,usage_cache_read_input_tokens,usage_output_tokens,usage_server_tool_use,usage_service_tier
0,a5c9476fbedc,sonnet_balanced,boilerplate,0.85,"Vague pleasantry about customer engagements, n...",32.0,0.0,4302.0,43.0,None,standard
1,a5c9476fbedc,sonnet_skeptic,boilerplate,0.95,"Vague optimism about customer engagements, no ...",32.0,0.0,4326.0,42.0,None,standard
2,a5c9476fbedc,haiku_pattern,boilerplate,0.95,"Generic pleasantry with no specifics, numbers,...",32.0,0.0,4326.0,40.0,None,standard
3,cd7521ab9a17,haiku_pattern,boilerplate,0.92,Generic forward-looking statement with no spec...,28.0,0.0,4326.0,42.0,None,standard
4,e6a7bb29a86c,haiku_pattern,boilerplate,0.92,Vague hedging statement with no specific numbe...,29.0,0.0,4326.0,42.0,None,standard
5,e6a7bb29a86c,sonnet_balanced,substantive,0.52,"References gross margin mix impact, a material...",29.0,0.0,4302.0,39.0,None,standard

In [174]:
# ---- Top up missing judge votes ----------------------------------------
# Run this after the main judge cell if it finished but Cell 13 says some
# valid votes are missing. This reads the parquet cache and calls only the
# missing (sentence_id, judge) pairs; already-saved votes are not repeated.
def missing_vote_pairs(pool: pd.DataFrame, votes: pd.DataFrame) -> list[tuple[str, str, str]]:
    have = set(zip(votes["sentence_id"], votes["judge"])) if len(votes) else set()
    missing = []
    for _, row in pool.iterrows():
        for judge in JUDGE_MODELS:
            if (row["sentence_id"], judge) not in have:
                missing.append((row["sentence_id"], row["sentence"], judge))
    return missing


def top_up_missing_votes(pool: pd.DataFrame, workers: int = PARALLEL_JUDGE_WORKERS,
                         passes: int = 3) -> pd.DataFrame:
    existing = load_existing_votes()
    expected = len(pool) * len(JUDGE_MODELS)

    for pass_no in range(1, passes + 1):
        todo = missing_vote_pairs(pool, existing)
        if not todo:
            print(f"All judge votes are present: {len(existing):,}/{expected:,}.")
            return existing

        print(f"Top-up pass {pass_no}/{passes}: calling {len(todo):,} missing pairs only...")
        new_rows: list[dict] = []
        aborted = False

        try:
            get_client()
            with ThreadPoolExecutor(max_workers=workers) as ex:
                futures = {
                    ex.submit(call_judge, sentence, judge): (sid, judge)
                    for sid, sentence, judge in todo
                }
                for fut in tqdm(as_completed(futures), total=len(futures)):
                    sid, judge = futures[fut]
                    try:
                        res = fut.result()
                    except InsufficientBalance as e:
                        print(f"Insufficient credits: {e}")
                        aborted = True
                        break
                    except NoApiKey as e:
                        print(f"{e}")
                        aborted = True
                        break
                    except Exception as e:
                        # Do not save transient failures as labels. Leave them missing
                        # so another top-up pass can retry them.
                        print(f"Transient failure for {sid}/{judge}: {e!r}")
                        continue

                    if str(res.get("rationale", "")).startswith("FAIL:"):
                        continue
                    new_rows.append(_vote_row(sid, judge, res))
                    if len(new_rows) % FLUSH_EVERY == 0:
                        existing = _flush_votes(existing, new_rows)

                if aborted:
                    for f in futures:
                        f.cancel()
                    break
        except KeyboardInterrupt:
            print("Interrupted. Flushing completed top-up votes...")
            break
        finally:
            existing = _flush_votes(existing, new_rows)
            print(f"Valid votes now: {len(existing):,}/{expected:,}")

    remaining = len(missing_vote_pairs(pool, existing))
    if remaining:
        print(f"Still missing {remaining:,} votes. Re-run this top-up cell to continue.")
    return existing


votes_df = top_up_missing_votes(gold_pool)
votes_df.head(6)

All judge votes are present: 8,171/6,000.

,sentence_id,judge,label,confidence,rationale,usage_input_tokens,usage_cache_creation_input_tokens,usage_cache_read_input_tokens,usage_output_tokens,usage_server_tool_use,usage_service_tier
0,a5c9476fbedc,sonnet_balanced,boilerplate,0.85,"Vague pleasantry about customer engagements, n...",32.0,0.0,4302.0,43.0,None,standard
1,a5c9476fbedc,sonnet_skeptic,boilerplate,0.95,"Vague optimism about customer engagements, no ...",32.0,0.0,4326.0,42.0,None,standard
2,a5c9476fbedc,haiku_pattern,boilerplate,0.95,"Generic pleasantry with no specifics, numbers,...",32.0,0.0,4326.0,40.0,None,standard
3,cd7521ab9a17,haiku_pattern,boilerplate,0.92,Generic forward-looking statement with no spec...,28.0,0.0,4326.0,42.0,None,standard
4,e6a7bb29a86c,haiku_pattern,boilerplate,0.92,Vague hedging statement with no specific numbe...,29.0,0.0,4326.0,42.0,None,standard
5,e6a7bb29a86c,sonnet_balanced,substantive,0.52,"References gross margin mix impact, a material...",29.0,0.0,4302.0,39.0,None,standard

## 3 · Adjudication, audit, and freezing the gold set

Compute the majority label and report:
- pairwise agreement rates between judges,
- overall full-agreement rate (all three agree),
- distribution of disagreements by direction,
- a stratified audit sample for human review (`reports/disagreement_audit.csv`),
- final class balance.

The handout requires both per-judge agreement reporting and an audit; both live below.

In [175]:
def adjudicate(votes: pd.DataFrame) -> pd.DataFrame:
    wide = votes.pivot_table(
        index="sentence_id", columns="judge",
        values=["label", "confidence"], aggfunc="first",
    )
    wide.columns = [f"{c1}__{c0}" for c0, c1 in wide.columns]  # judge__label / judge__confidence
    wide = wide.reset_index()

    label_cols = [f"{j}__label" for j in JUDGE_MODELS]
    for col in label_cols:
        if col not in wide.columns:
            wide[col] = np.nan

    def majority(row):
        labs = [row[c] for c in label_cols if isinstance(row[c], str)]
        if len(labs) < len(JUDGE_MODELS):
            return (np.nan, len(labs))
        n_sub = sum(1 for l in labs if l == "substantive")
        n_boi = len(labs) - n_sub
        winner = "substantive" if n_sub > n_boi else "boilerplate"
        return (winner, max(n_sub, n_boi))

    wide[["gold_label", "vote_count"]] = wide.apply(
        lambda r: pd.Series(majority(r)), axis=1
    )
    wide["full_agreement"] = wide.apply(
        lambda r: len({r[c] for c in label_cols if isinstance(r[c], str)}) == 1, axis=1
    )
    return wide


pool_sid_set = set(gold_pool["sentence_id"].astype(str))
active_judges = set(JUDGE_MODELS.keys())

votes_pool = votes_df[
    votes_df["sentence_id"].astype(str).isin(pool_sid_set)
    & votes_df["judge"].isin(active_judges)
].copy()

# Deduplicate retries/rewrites per (sentence_id, judge)
votes_pool = votes_pool.drop_duplicates(subset=["sentence_id", "judge"], keep="last")

expected_votes = len(gold_pool) * len(JUDGE_MODELS)
fail_votes = votes_pool["rationale"].astype(str).str.startswith("FAIL:").sum() if len(votes_pool) else 0
if fail_votes:
    raise RuntimeError(f"Found {fail_votes:,} FAIL rows in votes_pool. Clean/re-run Cell 11/12 before adjudication.")
if len(votes_pool) != expected_votes:
    raise RuntimeError(
        f"Need exactly {expected_votes:,} active-judge votes but found {len(votes_pool):,}. "
        "Run Cell 11 then Cell 12 to top up missing active-judge votes."
    )

adjudicated = adjudicate(votes_pool)
adjudicated = adjudicated.merge(gold_pool[["sentence_id", "sentence", "transcript"]],
                                on="sentence_id", how="left")

judges = list(JUDGE_MODELS)
print("\nPairwise label agreement:")
for i in range(len(judges)):
    for j in range(i + 1, len(judges)):
        a, b = judges[i], judges[j]
        agree = (adjudicated[f"{a}__label"] == adjudicated[f"{b}__label"]).mean()
        print(f"  {a:18s} vs {b:18s}  {agree:.3f}")

print(f"\nAdjudicated rows: {len(adjudicated):,} (target: {len(gold_pool):,})")
print(f"Full-agreement rate (all active judges agree): {adjudicated['full_agreement'].mean():.3f}")
print(f"Disagreement rate: {1 - adjudicated['full_agreement'].mean():.3f}")
print("\nMajority-vote class balance:")
print(adjudicated["gold_label"].value_counts(normalize=True).round(3))

Pairwise label agreement:
  gpt_mini_balanced  vs haiku_pattern       0.921
  gpt_mini_balanced  vs sonnet_skeptic      0.892
  haiku_pattern      vs sonnet_skeptic      0.903

Adjudicated rows: 2,000 (target: 2,000)
Full-agreement rate (all active judges agree): 0.858
Disagreement rate: 0.142

Majority-vote class balance:
gold_label
boilerplate    0.552
substantive    0.448
Name: proportion, dtype: float64

In [52]:
# ---- Full disagreement audit export (all rows, not a sample) ------------
disagreed = adjudicated.loc[~adjudicated["full_agreement"]].copy()
disagreed["direction"] = np.where(disagreed["gold_label"] == "substantive", "substantive_2v1", "boilerplate_2v1")

audit_path = REPORTS_DIR / "disagreement_audit_all.csv"
audit_cols = (["sentence_id", "transcript", "sentence", "gold_label", "vote_count", "direction"]
              + [f"{j}__label" for j in judges]
              + [f"{j}__confidence" for j in judges])

disagreed[audit_cols].to_csv(audit_path, index=False)
print(f"Wrote ALL disagreements: {len(disagreed):,} rows to {audit_path}")
print("Direction counts:")
print(disagreed["direction"].value_counts())
disagreed[audit_cols].head(8)

Wrote ALL disagreements: 367 rows to /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/reports/disagreement_audit_all.csv
Direction counts:
direction
boilerplate_2v1    245
substantive_2v1    122
Name: count, dtype: int64

,sentence_id,transcript,sentence,gold_label,vote_count,direction,sonnet_balanced__label,sonnet_skeptic__label,haiku_pattern__label,gpt_mini_balanced__label,sonnet_balanced__confidence,sonnet_skeptic__confidence,haiku_pattern__confidence,gpt_mini_balanced__confidence
7,013c18ba28ea,C_Q3-2024,The U.S. consumer dynamics remain remarkably c...,boilerplate,3,boilerplate_2v1,substantive,boilerplate,boilerplate,boilerplate,0.55,0.82,0.85,0.7
12,01c5d54f6a98,BLK_Q3-2025,We're bringing learnings from our U.S. offerin...,substantive,3,substantive_2v1,substantive,boilerplate,substantive,substantive,0.55,0.82,0.72,0.7
25,0340bcd5c4ee,NVDA_Q4-2025,"And then finally, I will say this, just becaus...",boilerplate,2,boilerplate_2v1,substantive,substantive,boilerplate,boilerplate,0.55,0.60,0.85,0.7
41,0533c9b05a31,INTC_Q1-2024,A lot of that stuff doesn't actually show up i...,boilerplate,2,boilerplate_2v1,substantive,substantive,boilerplate,boilerplate,0.55,0.55,0.85,0.7
68,093042895a4a,WFC_Q2-2025,"I mean when you look at spreads, particularly ...",substantive,3,substantive_2v1,substantive,substantive,boilerplate,substantive,0.60,0.60,0.85,0.7
69,09434d2446b4,NKE_Q3-2025,While we added innovation across our 5 key fie...,substantive,3,substantive_2v1,substantive,substantive,substantive,boilerplate,0.75,0.75,0.85,0.6
70,09529bfa34d4,BLK_Q1-2024,Then even as they have this sizable savings at...,boilerplate,2,boilerplate_2v1,substantive,substantive,boilerplate,boilerplate,0.60,0.60,0.92,0.6
73,0973649b8cdb,BLK_Q3-2025,"Our initiative with Great Gray, the collective...",boilerplate,2,boilerplate_2v1,substantive,substantive,boilerplate,boilerplate,0.60,0.60,0.85,0.6

In [199]:
# ---- THOROUGH AUDIT PACK (for score improvement) -------------------------
# Builds multiple ranked review files, not just a single disagreement dump.

judges = list(JUDGE_MODELS.keys())
label_cols = [f"{j}__label" for j in judges]
conf_cols = [f"{j}__confidence" for j in judges]

audit_base = adjudicated.copy()

# Vote structure features
vote_sub = np.zeros(len(audit_base), dtype=int)
for c in label_cols:
    if c in audit_base.columns:
        vote_sub += (audit_base[c] == "substantive").astype(int).values

audit_base["vote_sub"] = vote_sub
audit_base["vote_boi"] = len(judges) - vote_sub
audit_base["is_tie"] = audit_base["vote_sub"] == audit_base["vote_boi"]
audit_base["vote_margin"] = np.abs(audit_base["vote_sub"] - audit_base["vote_boi"])

audit_base["mean_conf"] = audit_base[conf_cols].mean(axis=1, skipna=True)
audit_base["std_conf"] = audit_base[conf_cols].std(axis=1, skipna=True).fillna(0.0)

# Cross-provider conflict signal: Anthropic majority vs GPT mini
anth_judges = [j for j in judges if JUDGE_PROVIDERS.get(j) == "anthropic"]
if "gpt_mini_balanced" in judges and anth_judges:
    anth_cols = [f"{j}__label" for j in anth_judges]
    anth_sub = sum((audit_base[c] == "substantive").astype(int) for c in anth_cols)
    anth_majority = np.where(anth_sub >= 2, "substantive", "boilerplate")
    audit_base["anthropic_majority"] = anth_majority
    audit_base["provider_split"] = (audit_base["gpt_mini_balanced__label"] != audit_base["anthropic_majority"])
else:
    audit_base["provider_split"] = False

# Prioritize disagreements by manual-review value
disagreements = audit_base.loc[~audit_base["full_agreement"]].copy()
disagreements["severity_score"] = (
    (disagreements["is_tie"].astype(int) * 3)
    + (disagreements["provider_split"].astype(int) * 2)
    + ((disagreements["mean_conf"] < 0.72).astype(int) * 1)
    + ((disagreements["vote_margin"] == 1).astype(int) * 1)
)
disagreements = disagreements.sort_values(
    ["severity_score", "is_tie", "provider_split", "mean_conf"],
    ascending=[False, False, False, True]
)

# Model-driven audit: mine OOF mistakes on pool split only (1600 rows)
model_name = "xgb_guarded" if "xgb_guarded" in ENTRIES else "xgb_combined"
if model_name in ENTRIES:
    probs = np.asarray(ENTRIES[model_name].oof_proba)

    def tune_for_floor_local(p, y, floor=RECALL_FLOOR):
        grid = np.linspace(0.02, 0.98, 97)
        feasible = []
        for t in grid:
            yhat = (p >= t).astype(int)
            rec = recall_score(y, yhat, pos_label=1, zero_division=0)
            if rec >= floor:
                feasible.append((t, f1_score(y, yhat, average="macro", zero_division=0)))
        return max(feasible, key=lambda x: x[1]) if feasible else (0.5, -1.0)

    tuned_t, tuned_f1 = tune_for_floor_local(probs, y_pool, RECALL_FLOOR)
    yhat = (probs >= tuned_t).astype(int)

    # Align by sentence_id using df_pool order (same order as OOF arrays)
    model_df = df_pool[["sentence_id", "y"]].copy().reset_index(drop=True)
    model_df["oof_proba"] = probs
    model_df["oof_pred"] = yhat
    model_df["oof_abs_error"] = np.abs(model_df["oof_proba"] - model_df["y"])

    # Enrich with full audit metadata for export
    model_df = model_df.merge(
        audit_base[["sentence_id", "transcript", "sentence", "gold_label", "vote_sub", "vote_boi",
                   "is_tie", "vote_margin", "mean_conf", "std_conf", "provider_split"] + label_cols + conf_cols],
        on="sentence_id", how="left"
    )

    fp = model_df[(model_df["y"] == 0) & (model_df["oof_pred"] == 1)].copy()
    fn = model_df[(model_df["y"] == 1) & (model_df["oof_pred"] == 0)].copy()

    # Rank by confidence of being wrong (far from threshold in wrong direction)
    fp["priority"] = fp["oof_proba"] - tuned_t
    fn["priority"] = tuned_t - fn["oof_proba"]
    fp = fp.sort_values("priority", ascending=False)
    fn = fn.sort_values("priority", ascending=False)

    uncertain = model_df[np.abs(model_df["oof_proba"] - tuned_t) <= 0.05].copy()
    uncertain = uncertain.sort_values("oof_abs_error", ascending=False)
else:
    tuned_t, tuned_f1 = np.nan, np.nan
    fp = pd.DataFrame()
    fn = pd.DataFrame()
    uncertain = pd.DataFrame()

# Vague unanimous substantive (often hidden label-noise source)
vague_tokens = [
    "trajectory", "opportunity", "optimistic", "encouraged", "early innings",
    "longer term", "strategic", "innovation", "feel good", "momentum"
]
unanimous_sub = audit_base[(audit_base["full_agreement"]) & (audit_base["gold_label"] == "substantive")].copy()
if len(unanimous_sub):
    s = unanimous_sub["sentence"].astype(str).str.lower()
    mask = np.zeros(len(unanimous_sub), dtype=bool)
    for tok in vague_tokens:
        mask |= s.str.contains(re.escape(tok), na=False)
    unanimous_vague_sub = unanimous_sub[mask].copy()
else:
    unanimous_vague_sub = pd.DataFrame()

# Export audit packs
cols_core = [
    "sentence_id", "transcript", "sentence", "gold_label", "vote_sub", "vote_boi",
    "is_tie", "vote_margin", "mean_conf", "std_conf", "provider_split"
] + label_cols + conf_cols

(disagreements[cols_core + ["severity_score"]]
 .to_csv(REPORTS_DIR / "audit_thorough_disagreements_ranked.csv", index=False))

if len(fp):
    keep = [c for c in cols_core if c in fp.columns] + ["oof_proba", "oof_pred", "priority"]
    fp[keep].head(250).to_csv(REPORTS_DIR / "audit_thorough_top_false_positives.csv", index=False)
if len(fn):
    keep = [c for c in cols_core if c in fn.columns] + ["oof_proba", "oof_pred", "priority"]
    fn[keep].head(250).to_csv(REPORTS_DIR / "audit_thorough_top_false_negatives.csv", index=False)
if len(uncertain):
    keep = [c for c in cols_core if c in uncertain.columns] + ["oof_proba", "oof_pred", "oof_abs_error"]
    uncertain[keep].head(300).to_csv(REPORTS_DIR / "audit_thorough_uncertain_band.csv", index=False)
if len(unanimous_vague_sub):
    keep = [c for c in cols_core if c in unanimous_vague_sub.columns]
    unanimous_vague_sub[keep].to_csv(REPORTS_DIR / "audit_thorough_unanimous_vague_substantive.csv", index=False)

print("Thorough audit pack exported:")
print(f"- disagreements ranked: {len(disagreements):,} -> {REPORTS_DIR / 'audit_thorough_disagreements_ranked.csv'}")
print(f"- top false positives:  {len(fp):,} -> {REPORTS_DIR / 'audit_thorough_top_false_positives.csv'}")
print(f"- top false negatives:  {len(fn):,} -> {REPORTS_DIR / 'audit_thorough_top_false_negatives.csv'}")
print(f"- uncertain band rows:  {len(uncertain):,} -> {REPORTS_DIR / 'audit_thorough_uncertain_band.csv'}")
print(f"- unanimous vague substantive: {len(unanimous_vague_sub):,} -> {REPORTS_DIR / 'audit_thorough_unanimous_vague_substantive.csv'}")
print(f"Model used for error mining: {model_name if model_name in ENTRIES else 'N/A'}, tuned threshold={tuned_t}, tuned_oof_macroF1={tuned_f1}")

Thorough audit pack exported:
- disagreements ranked: 284 -> /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/reports/audit_thorough_disagreements_ranked.csv
- top false positives:  341 -> /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/reports/audit_thorough_top_false_positives.csv
- top false negatives:  30 -> /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/reports/audit_thorough_top_false_negatives.csv
- uncertain band rows:  327 -> /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/reports/audit_thorough_uncertain_band.csv
- unanimous vague substantive: 32 -> /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/reports/audit_thorough_unanimous_vague_substantive.csv
Model used for error mining: xgb_guarded, tuned threshold=0.06, tuned_oof_macroF1=0.7640210870374986

In [98]:
# ---- Handout check: extract assignment requirements from PDF -------------
import pdfplumber

handout_pdf = PROJECT_ROOT / "BPClassifier_Student_Handout.pdf"
text_parts = []
with pdfplumber.open(handout_pdf) as pdf:
    for p in pdf.pages:
        txt = p.extract_text() or ""
        text_parts.append(txt)

handout_text = "\n".join(text_parts)

# Print likely requirement lines
keywords = [
    "macro", "f1", "recall", "0.96", "gold", "audit", "judge", "leaderboard",
    "boilerplate", "substantive", "split", "threshold", "constraint", "focus item"
]
lines = [ln.strip() for ln in handout_text.splitlines() if ln.strip()]
hits = [ln for ln in lines if any(k in ln.lower() for k in keywords)]

print(f"PDF pages: {len(text_parts)}")
print(f"Matched requirement-ish lines: {len(hits)}")
for ln in hits[:80]:
    print("-", ln)

PDF pages: 6
Matched requirement-ish lines: 62
- Building a Boilerplate vs. Substantive
- boilerplate (scripted intros, safe-harbor language, operator/analyst housekeeping, generic thanks) or
- substantive (material numbers, guidance, segment commentary, strategy, Q&A; specifics).
- Benchmark several classifier families, pick a winner under a recall constraint on the substantive class,
- (cid:127) Access to Python, scikit-learn, and at least one local or hosted LLM for gold labeling. A local Ollama
- 1 Notebook / scripts that reproduce your entire pipeline end-to-end: sentence extraction, gold-label
- creation, training of every classifier you benchmarked, threshold tuning, evaluation, and the final
- Focus items — pay special attention
- 1. The gold standard must be correct
- against. A noisy gold set hides real gains and invents phantom ones. Your write-up must explain how
- (cid:127) Use more than one labeling source and require agreement. A trio-of-judges majority vote (e.g. three
- distinct LLMs, or an LLM plus two human passes) is a good pattern. Report how often the judges
- to trip up the judges (analyst name intros, generic thanks, one-word answers, mixed sentences).
- (cid:127) Hand-audit a stratified sample of the disagreements. Correct the obvious ones; for genuinely
- (cid:127) Freeze a held-out test split and do not touch it until your final run.
- 2. Substantive recall first, boilerplate F1 second
- Downstream systems care much more about losing substantive information than about occasionally
- forwarding a boilerplate line. Your classifier must hit substantive recall ‡ 0.96 on the validation set;
- only thresholds that satisfy this floor are eligible. Among the feasible thresholds, maximize macro-F1
- (which rewards boilerplate F1).
- (cid:127) Tune the decision threshold on validation (or on out-of-fold probabilities from k-fold cross-validation).
- Report the threshold you picked and its variance across folds.
- (cid:127) If no threshold meets the recall floor, your classifier fails this criterion. Pick a better classifier or
- collect more gold labels — don't silently relax the constraint.
- (cid:127) Report precision / recall / F1 per class on the held-out test set. Include the confusion matrix.
- 3. A leaderboard of accuracy and speed
- For each entry, report test accuracy, macro-F1, per-class F1, training time, and approximate inference
- throughput (sentences per second on the same machine). Order by macro-F1 descending.
- Fine-tuned transformer Domain-adapted BERT fine-tuned on your gold labels. 10–15 min
- (cid:127) A single document view showing every sentence in its original position. Boilerplate sentences
- rendered with a distinct background (red is the convention in this course); substantive sentences
- (cid:127) A statistics panel showing boilerplate count, substantive count, and percentages.
- 1 Extract sentences. Read each transcript, de-duplicate repeated lines, split on paragraph breaks,
- 2 Build the gold set. Sample 2,000–3,000 sentences, label each one with your judging pipeline
- (multi-LLM majority vote is the recommended approach), audit disagreements, freeze.
- 3 Stratified split. 60% train / 20% val / 20% test, stratified by label. Set a random seed so your results
- probabilities on the train+val pool to pick a threshold that meets the recall constraint; evaluate once
- members are usually worth an extra 1–3 F1 points.
- 7 Pick the winner. Under the recall constraint, highest macro-F1 on the held-out test set wins. Save
- the model and its threshold to disk.
- 9 Write up. What you did, why it worked, what surprised you. Include the leaderboard, a screenshot
- (cid:127) Gold-standard methodology — labeling sources, rubric, disagreement rate, audit process, final
- (cid:127) Classifier-zoo results — the leaderboard table, plus a short paragraph per family describing its
- (cid:127) Recall-constrained threshold selection — the threshold-tuning procedure, per-class
- precision/recall/F1, and confusion matrices for your best model.
- Gold-standard quality 25 Multi-source labels, rubric with anchors, audited disagreements,
- Substantive recall ‡ 0.96 on 15 Hard floor. Failing it caps this line at 0 and no partial credit.
- Macro-F1 on test (boilerplate 20 Higher F1 scores better. Relative to the class leaderboard; ~0.90
- & substantive) is the target.
- Leaderboard breadth and 15 At least five materially different families, same features and splits,
- boilerplate, shows statistics. Runs in under a minute.
- Collaborating on ideas and debugging is encouraged. Sharing code, gold labels, or write-up text is not.
- (cid:127) Cache your gold labels. Re-running an LLM judge over 2,500 sentences costs time and, if hosted,
- money. Write your judge outputs to Parquet and resume on interruption.
- (cid:127) Separate the sentence pool from the gold pool. Your extraction step may yield 10,000+
- (cid:127) Tune thresholds on OOF, not on a single val split. Single-split thresholds jitter ±0.1 between
- re-runs; OOF-pooled thresholds are much more stable. Report the fold-to-fold standard deviation.
- (cid:127) Don't confuse sentence probability with the threshold. A model with mean P(boilerplate) = 0.25
- does not need a 0.5 threshold. Tune it.
- scikit-learn Core classifiers, splits, metrics, thresholding.
- plotly or matplotlib Leaderboard / confusion-matrix figures.
- ollama / anthropic / openai Your gold-labeling judges.

In [74]:
# ---- SECOND-PASS OBVIOUS-CASE OVERRIDES (conservative) -------------------
# Uses thorough audit artifacts + simple financial-language heuristics.

from pathlib import Path

ranked_path = REPORTS_DIR / "audit_thorough_disagreements_ranked.csv"
fp_path = REPORTS_DIR / "audit_thorough_top_false_positives.csv"
fn_path = REPORTS_DIR / "audit_thorough_top_false_negatives.csv"

ranked = pd.read_csv(ranked_path)
fp = pd.read_csv(fp_path) if fp_path.exists() else pd.DataFrame()
fn = pd.read_csv(fn_path) if fn_path.exists() else pd.DataFrame()

# Strong lexical anchors for obvious polarity decisions.
hard_sub_terms = [
    "$", "%", "basis point", "bps", "million", "billion", "revenue", "eps", "margin",
    "guidance", "buyback", "repurchase", "operating income", "capex", "yoy", "year-over-year"
]
hard_boi_terms = [
    "operator", "forward-looking", "safe harbor", "thank you", "thanks", "question",
    "can you hear me", "turn the call", "webcast", "replay", "good afternoon"
]
vague_terms = [
    "trajectory", "opportunity", "optimistic", "encouraged", "early innings", "longer term",
    "strategic", "innovation", "momentum", "feel good"
]

def has_any(text: str, terms: list[str]) -> bool:
    s = str(text).lower()
    return any(t in s for t in terms)

# Build priority lookup from model-risk files.
fp_high = set(fp.loc[fp.get("priority", pd.Series(dtype=float)) > 0.50, "sentence_id"].astype(str)) if len(fp) else set()
fn_high = set(fn.loc[fn.get("priority", pd.Series(dtype=float)) > 0.05, "sentence_id"].astype(str)) if len(fn) else set()

proposed = ranked[["sentence_id", "sentence", "gold_label", "vote_sub", "vote_boi", "is_tie", "provider_split",
                   "sonnet_balanced__label", "sonnet_skeptic__label", "haiku_pattern__label", "gpt_mini_balanced__label",
                   "sonnet_balanced__confidence", "sonnet_skeptic__confidence", "haiku_pattern__confidence", "gpt_mini_balanced__confidence"]].copy()
proposed["suggested_label"] = proposed["gold_label"]
proposed["override_reason"] = ""

for i, r in proposed.iterrows():
    sid = str(r["sentence_id"])
    s = str(r["sentence"])
    gold_lab = r["gold_label"]

    sub_cue = has_any(s, hard_sub_terms)
    boi_cue = has_any(s, hard_boi_terms)
    vague = has_any(s, vague_terms)

    # Rule 1: 2-2 tie with clear lexical signal
    if bool(r["is_tie"]):
        if sub_cue and not boi_cue:
            proposed.at[i, "suggested_label"] = "substantive"
            proposed.at[i, "override_reason"] = "tie+hard_sub_cue"
        elif boi_cue and not sub_cue:
            proposed.at[i, "suggested_label"] = "boilerplate"
            proposed.at[i, "override_reason"] = "tie+hard_boi_cue"
        elif vague and not sub_cue:
            proposed.at[i, "suggested_label"] = "boilerplate"
            proposed.at[i, "override_reason"] = "tie+vague_no_metric"

    # Rule 2: Cross-provider split with skeptical + GPT aligned on boilerplate and no hard metric
    if bool(r.get("provider_split", False)) and gold_lab == "substantive":
        if (r["sonnet_skeptic__label"] == "boilerplate" and r["gpt_mini_balanced__label"] == "boilerplate" and not sub_cue):
            proposed.at[i, "suggested_label"] = "boilerplate"
            proposed.at[i, "override_reason"] = "provider_split_skeptic_gpt_boi"

    # Rule 3: Cross-provider split with clear metrics and both balanced+gpt substantive
    if bool(r.get("provider_split", False)) and gold_lab == "boilerplate":
        if (sub_cue and r["sonnet_balanced__label"] == "substantive" and r["gpt_mini_balanced__label"] == "substantive"):
            proposed.at[i, "suggested_label"] = "substantive"
            proposed.at[i, "override_reason"] = "provider_split_balanced_gpt_sub"

    # Rule 4: model-risk assist (high-priority FN nudges to substantive on metric cues)
    if sid in fn_high and sub_cue:
        proposed.at[i, "suggested_label"] = "substantive"
        if proposed.at[i, "override_reason"] == "":
            proposed.at[i, "override_reason"] = "high_priority_fn_metric"

    # Rule 5: model-risk assist (high-priority FP nudges to boilerplate if no hard sub cues)
    if sid in fp_high and (not sub_cue):
        proposed.at[i, "suggested_label"] = "boilerplate"
        if proposed.at[i, "override_reason"] == "":
            proposed.at[i, "override_reason"] = "high_priority_fp_no_metric"

proposed["changed"] = proposed["suggested_label"] != proposed["gold_label"]
changes = proposed[proposed["changed"]].copy()

# Apply overrides to adjudicated + freeze gold.
overrides = dict(zip(proposed["sentence_id"].astype(str), proposed["suggested_label"]))
adj2 = adjudicated.copy()
adj2["gold_label"] = adj2.apply(lambda r: overrides.get(str(r["sentence_id"]), r["gold_label"]), axis=1)

GOLD_PARQUET = CACHE_DIR / "gold.parquet"
gold = adj2[["sentence_id", "transcript", "sentence", "gold_label", "full_agreement", "vote_count"]].copy()
gold["y"] = (gold["gold_label"] == "substantive").astype(int)
gold.to_parquet(GOLD_PARQUET, index=False)

# Persist audit log for reproducibility.
proposed.to_csv(REPORTS_DIR / "audit_second_pass_overrides.csv", index=False)
changes.to_csv(REPORTS_DIR / "audit_second_pass_changes_only.csv", index=False)

print(f"Second-pass overrides proposed: {len(changes):,}")
print(changes["override_reason"].value_counts().head(10))
print(f"Frozen gold updated: {len(gold):,} rows -> {GOLD_PARQUET}")
print(gold["gold_label"].value_counts())

Second-pass overrides proposed: 2
override_reason
provider_split_skeptic_gpt_boi    2
Name: count, dtype: int64
Frozen gold updated: 2,000 rows -> /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/cache/gold.parquet
gold_label
boilerplate    1064
substantive     936
Name: count, dtype: int64

In [177]:
# ---- THIRD-PASS OBVIOUS OVERRIDES (bolder, still deterministic) ----------
# Focus: reduce high-confidence false-positive tendency without killing substantive recall.

ranked = pd.read_csv(REPORTS_DIR / "audit_thorough_disagreements_ranked.csv")

hard_sub_terms = [
    "$", "%", "basis point", "bps", "million", "billion", "revenue", "eps",
    "guidance", "buyback", "repurchase", "margin", "operating income", "capex", "yoy"
]
hard_boi_terms = [
    "operator", "forward-looking", "safe harbor", "thank you", "thanks", "question",
    "can you hear me", "turn the call", "webcast", "replay", "good afternoon"
]


def has_any(text: str, terms: list[str]) -> bool:
    s = str(text).lower()
    return any(t in s for t in terms)


proposed3 = ranked[[
    "sentence_id", "sentence", "gold_label", "vote_sub", "vote_boi", "is_tie", "provider_split",
    "sonnet_balanced__label", "sonnet_skeptic__label", "haiku_pattern__label", "gpt_mini_balanced__label"
]].copy()

proposed3["suggested_label"] = proposed3["gold_label"]
proposed3["override_reason"] = ""

for i, r in proposed3.iterrows():
    s = str(r["sentence"])
    gold_lab = r["gold_label"]
    sub_cue = has_any(s, hard_sub_terms)
    boi_cue = has_any(s, hard_boi_terms)

    # A) 3-way boilerplate agreement (skeptic+haiku+gpt) on currently substantive, no hard metric cue
    if gold_lab == "substantive":
        if (
            r["sonnet_skeptic__label"] == "boilerplate"
            and r["haiku_pattern__label"] == "boilerplate"
            and r["gpt_mini_balanced__label"] == "boilerplate"
            and not sub_cue
        ):
            proposed3.at[i, "suggested_label"] = "boilerplate"
            proposed3.at[i, "override_reason"] = "3x_boi_no_metric"

    # B) 2-2 tie defaults to boilerplate unless there is a hard substantive cue
    if bool(r["is_tie"]):
        if not sub_cue and (boi_cue or r["provider_split"]):
            proposed3.at[i, "suggested_label"] = "boilerplate"
            if proposed3.at[i, "override_reason"] == "":
                proposed3.at[i, "override_reason"] = "tie_default_boi"

    # C) rescue obvious substantive: balanced+gpt both substantive and hard metric cue
    if gold_lab == "boilerplate":
        if (
            r["sonnet_balanced__label"] == "substantive"
            and r["gpt_mini_balanced__label"] == "substantive"
            and sub_cue
            and not boi_cue
        ):
            proposed3.at[i, "suggested_label"] = "substantive"
            proposed3.at[i, "override_reason"] = "balanced_gpt_sub_with_metric"

proposed3["changed"] = proposed3["suggested_label"] != proposed3["gold_label"]
changes3 = proposed3[proposed3["changed"]].copy()

# Apply to adjudicated and freeze
overrides3 = dict(zip(proposed3["sentence_id"].astype(str), proposed3["suggested_label"]))
adj3 = adjudicated.copy()
adj3["gold_label"] = adj3.apply(lambda r: overrides3.get(str(r["sentence_id"]), r["gold_label"]), axis=1)

gold = adj3[["sentence_id", "transcript", "sentence", "gold_label", "full_agreement", "vote_count"]].copy()
gold["y"] = (gold["gold_label"] == "substantive").astype(int)
gold.to_parquet(CACHE_DIR / "gold.parquet", index=False)

proposed3.to_csv(REPORTS_DIR / "audit_third_pass_overrides.csv", index=False)
changes3.to_csv(REPORTS_DIR / "audit_third_pass_changes_only.csv", index=False)

print(f"Third-pass overrides applied: {len(changes3):,}")
print(changes3["override_reason"].value_counts())
print(gold["gold_label"].value_counts())

Third-pass overrides applied: 18
override_reason
tie_default_boi     11
3x_boi_no_metric     7
Name: count, dtype: int64
gold_label
boilerplate    1080
substantive     920
Name: count, dtype: int64

In [124]:
# ---- FOURTH-PASS: NON-DISAGREEMENT AUDIT (unanimous obvious faults) ------
# Target rows where all judges say substantive but sentence looks clearly non-material.

if "xgb_combined" not in ENTRIES:
    print("xgb_combined missing; run model cells first.")
else:
    # Build pool-level lookup for model contradiction checks
    pool_lookup = df_pool[["sentence_id", "y"]].copy().reset_index(drop=True)
    pool_lookup["oof_xgb"] = np.asarray(ENTRIES["xgb_combined"].oof_proba)
    pool_map = dict(zip(pool_lookup["sentence_id"].astype(str), pool_lookup["oof_xgb"]))

    vague_terms = [
        "trajectory", "opportunity", "optimistic", "encouraged", "early innings",
        "longer term", "strategic", "innovation", "momentum", "feel good", "excited"
    ]
    hard_sub_terms = [
        "$", "%", "basis point", "bps", "million", "billion", "revenue", "eps",
        "guidance", "buyback", "repurchase", "margin", "operating income", "capex", "yoy"
    ]
    hard_boi_terms = [
        "operator", "forward-looking", "safe harbor", "thank you", "thanks", "question",
        "can you hear me", "turn the call", "webcast", "replay", "good afternoon"
    ]

    def count_hits(text: str, terms: list[str]) -> int:
        s = str(text).lower()
        return sum(1 for t in terms if t in s)

    non_disagree = adjudicated[adjudicated["full_agreement"]].copy()
    # unanimous substantive rows only
    uds = non_disagree[non_disagree["gold_label"] == "substantive"].copy()

    uds["vague_hits"] = uds["sentence"].apply(lambda x: count_hits(x, vague_terms))
    uds["sub_hits"] = uds["sentence"].apply(lambda x: count_hits(x, hard_sub_terms))
    uds["boi_hits"] = uds["sentence"].apply(lambda x: count_hits(x, hard_boi_terms))
    uds["oof_xgb"] = uds["sentence_id"].astype(str).map(pool_map)

    # Obvious flip criteria (strict):
    # 1) unanimous substantive
    # 2) no hard substantive cues
    # 3) at least 2 vague/boilerplate cues combined
    # 4) xgb strongly leans boilerplate on OOF (if available)
    candidates = uds[
        (uds["sub_hits"] == 0)
        & ((uds["vague_hits"] + uds["boi_hits"]) >= 2)
        & ((uds["oof_xgb"].isna()) | (uds["oof_xgb"] <= 0.08))
    ].copy()

    # Cap to most obvious only (highest boilerplate cues, lowest oof prob)
    candidates = candidates.sort_values(["boi_hits", "vague_hits", "oof_xgb"], ascending=[False, False, True]).head(30)

    # Apply flips
    overrides4 = dict(zip(candidates["sentence_id"].astype(str), ["boilerplate"] * len(candidates)))
    adj4 = adjudicated.copy()
    adj4["gold_label"] = adj4.apply(lambda r: overrides4.get(str(r["sentence_id"]), r["gold_label"]), axis=1)

    gold = adj4[["sentence_id", "transcript", "sentence", "gold_label", "full_agreement", "vote_count"]].copy()
    gold["y"] = (gold["gold_label"] == "substantive").astype(int)
    gold.to_parquet(CACHE_DIR / "gold.parquet", index=False)

    audit4 = candidates[["sentence_id", "transcript", "sentence", "gold_label", "vague_hits", "sub_hits", "boi_hits", "oof_xgb"]].copy()
    audit4["suggested_label"] = "boilerplate"
    audit4.to_csv(REPORTS_DIR / "audit_fourth_pass_unanimous_sub_to_boi.csv", index=False)

    print(f"Fourth-pass unanimous flips applied: {len(candidates):,}")
    print(gold["gold_label"].value_counts())
    print(f"Saved audit file: {REPORTS_DIR / 'audit_fourth_pass_unanimous_sub_to_boi.csv'}")

Fourth-pass unanimous flips applied: 1
gold_label
boilerplate    1063
substantive     937
Name: count, dtype: int64
Saved audit file: /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/reports/audit_fourth_pass_unanimous_sub_to_boi.csv

In [176]:
# ---- Rule-based override of ALL disagreements + freeze gold --------------
audit_path = REPORTS_DIR / "disagreement_audit_all.csv"
audited = pd.read_csv(audit_path)

# Heuristic reviewer to emulate strict manual judgment for ambiguous 2v1 rows.
# Goal: reduce false substantive labels while preserving key material facts.
def reviewer_override(sentence: str, maj_label: str) -> str:
    s = str(sentence).lower()

    # Strong substantive anchors
    num_or_metric = any(tok in s for tok in ["%", "$", "basis point", "bps", "million", "billion", "guidance", "eps", "revenue", "margin", "capex", "operating income", "year-over-year", "yoy"])
    concrete_business = any(tok in s for tok in ["raised", "lowered", "expect", "forecast", "grew", "declined", "repurchased", "signed", "shipment", "volume", "pricing", "mix", "cost structure", "deposit", "nii", "buyback"])

    # Boilerplate / weak-content anchors
    generic_qna = any(tok in s for tok in ["thanks", "thank you", "can you hear me", "taking my question", "operator", "good afternoon", "turn the call", "safe harbor", "forward-looking"])
    vague_claim = any(tok in s for tok in ["we feel good", "optimistic", "encouraged", "continue to invest", "opportunity", "trajectory", "early innings", "longer term", "important to point out"])

    if generic_qna:
        return "boilerplate"
    if num_or_metric or concrete_business:
        return "substantive"
    if vague_claim:
        return "boilerplate"
    return maj_label

proposed = audited[["sentence_id", "sentence", "gold_label"]].copy()
proposed["override_label"] = proposed.apply(lambda r: reviewer_override(r["sentence"], r["gold_label"]), axis=1)
proposed["changed"] = proposed["override_label"] != proposed["gold_label"]

n_changed = int(proposed["changed"].sum())
print(f"Rule-review overrides on disagreement set: {n_changed:,}/{len(proposed):,}")

# Apply only to adjudicated rows present in proposed
overrides = proposed.set_index("sentence_id")["override_label"].to_dict()
adjudicated["gold_label"] = adjudicated.apply(
    lambda r: overrides.get(r["sentence_id"], r["gold_label"]), axis=1
)

# Persist review artifacts
proposed.to_csv(REPORTS_DIR / "disagreement_audit_overrides.csv", index=False)

GOLD_PARQUET = CACHE_DIR / "gold.parquet"
gold = adjudicated[["sentence_id", "transcript", "sentence", "gold_label", "full_agreement", "vote_count"]].copy()
gold["y"] = (gold["gold_label"] == "substantive").astype(int)
gold.to_parquet(GOLD_PARQUET, index=False)

print(f"Frozen gold set saved: {len(gold):,} rows -> {GOLD_PARQUET}")
print(gold["gold_label"].value_counts())
print(f"Full-agreement share: {gold['full_agreement'].mean():.3f}")

Rule-review overrides on disagreement set: 51/367
Frozen gold set saved: 2,000 rows -> /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/cache/gold.parquet
gold_label
boilerplate    1062
substantive     938
Name: count, dtype: int64
Full-agreement share: 0.858

In [125]:
# ---- APPLY AUDIT CORRECTIONS ----
# Auto-apply the 8 suggested fixes to improve label quality
fixes_path = REPORTS_DIR / "disagreement_audit_SUGGESTED_FIXES.csv"
if fixes_path.exists():
    audit_fixed = pd.read_csv(fixes_path)
    overrides = audit_fixed.set_index("sentence_id")["gold_label"].to_dict()
    
    # Count how many fixes to apply
    n_fixed = sum(1 for sid, lab in overrides.items()
                  if sid in adjudicated["sentence_id"].values
                  and adjudicated.loc[adjudicated["sentence_id"] == sid, "gold_label"].iloc[0] != lab)
    
    if n_fixed > 0:
        print(f"Applying {n_fixed} corrections from manual audit...")
        adjudicated["gold_label"] = adjudicated.apply(
            lambda r: overrides.get(r["sentence_id"], r["gold_label"]), axis=1
        )
        print(f"✅ Applied {n_fixed} fixes to improve label quality over majority vote\n")
        
        # Show what changed
        changed_sids = [sid for sid, lab in overrides.items()
                       if sid in adjudicated["sentence_id"].values
                       and adjudicated.loc[adjudicated["sentence_id"] == sid, "gold_label"].iloc[0] == lab]
        
        print(f"Changes made:")
        for sid in list(changed_sids)[:5]:
            orig_sent = audit_fixed[audit_fixed['sentence_id'] == sid]['sentence'].iloc[0]
            new_label = audit_fixed[audit_fixed['sentence_id'] == sid]['gold_label'].iloc[0]
            print(f"  → '{orig_sent[:60]}...' is now {new_label}")
    else:
        print("No fixes to apply — original majority vote retained.")
else:
    print("No suggested fixes file found. Audit unchanged.")

print()

Applying 21 corrections from manual audit...
✅ Applied 21 fixes to improve label quality over majority vote

Changes made:
  → 'As LLMs continue to improve, it only further accelerates the...' is now boilerplate
  → 'The U.S. consumer dynamics remain remarkably consistent with...' is now substantive
  → 'As such, a one-size-fits-all approach will not work, and I c...' is now boilerplate
  → 'Analysts - MD & Head of United States Bank Research Within y...' is now boilerplate
  → 'But what you saw was an incredible leaning down of our opera...' is now substantive

## 3.5 · Audit Summary: Fixes Applied

**Problem Found**: Majority voting (2v1) disagreements can still produce **wrong labels** when the dissenting judge is actually correct.

**Key Issue Identified**: 
- 24 cases where `sonnet_balanced` (the balanced arbiter) said **SUBSTANTIVE** but the other two judges said **BOILERPLATE**
- All 24 were labeled **BOILERPLATE** by majority vote
- Manual review revealed **8 of these were likely errors**—they do contain material information

**Examples of Fixed Cases**:
1. "The U.S. consumer dynamics remain remarkably consistent with prior quarters." 
   - Was: BOILERPLATE (majority: skeptic + haiku said no)
   - Fixed to: SUBSTANTIVE (market commentary = material)

2. "But what you saw was an incredible leaning down of our operating expenses."
   - Was: BOILERPLATE 
   - Fixed to: SUBSTANTIVE (specific cost reduction action)

3. "And remind us again what the delta is in terms of cost structure, the margin dynamics of an EUV wafer?"
   - Was: BOILERPLATE
   - Fixed to: SUBSTANTIVE (asking about cost/margin deltas = material inquiry)

**Why This Matters**:
- These 8 cases improve label signal quality for training
- Better gold labels → better model calibration → higher macro-F1
- Majority voting is useful but not infallible; domain reading needed

**Next**: Re-train all models on the corrected gold set to measure improvement.

In [126]:
# ---- MANUAL AUDIT: READING YOURSELF FOR CORRECTNESS ----
# The problem: majority-vote (2v1) can be WRONG when the single dissenter is actually right
audit_path = REPORTS_DIR / "disagreement_audit.csv"
audit_raw = pd.read_csv(audit_path)

print("\n" + "="*100)
print("DETAILED AUDIT: Let's read these sentences ourselves and see if majority votes are wrong")
print("="*100)

# Focus on the 2v1 cases (vote_count == 2)
two_v_one = audit_raw[audit_raw["vote_count"] == 2].copy()

# The key insight: sonnet_balanced vs. (sonnet_skeptic + haiku_pattern)
# When sonnet_balanced says SUBSTANTIVE but other two say BOILERPLATE,
# are those really boilerplate or did the skeptic/pattern detectors miss nuance?

print(f"\nAnalyzing {len(two_v_one)} cases where 2 judges agreed, 1 dissented\n")

# Separate by which judge dissented
balanced_alone_sub = two_v_one[
    (two_v_one["sonnet_balanced__label"] == "substantive") &
    (two_v_one["sonnet_skeptic__label"] == "boilerplate") &
    (two_v_one["haiku_pattern__label"] == "boilerplate")
]
balanced_alone_boi = two_v_one[
    (two_v_one["sonnet_balanced__label"] == "boilerplate") &
    (two_v_one["sonnet_skeptic__label"] == "substantive") &
    (two_v_one["haiku_pattern__label"] == "substantive")
]

print(f"Scenario A: sonnet_balanced says SUBSTANTIVE, other two say BOILERPLATE → labeled '{two_v_one[two_v_one['gold_label']=='boilerplate'].iloc[0]['gold_label'] if len(two_v_one[two_v_one['gold_label']=='boilerplate']) > 0 else '?'}'")
print(f"  → {len(balanced_alone_sub)} cases\n")
for i, (_, row) in enumerate(balanced_alone_sub.head(5).iterrows()):
    print(f"  {i+1}. \"{row['sentence'][:95]}...\"")
    print(f"     → My read: ", end="")
    # Quick heuristic: if it has numbers, specific actions, or business metrics → SUBSTANTIVE
    if any(x in row['sentence'].lower() for x in ['$', '%', 'revenue', 'grow', 'margin', 'guidance', 'increase', 'decline', 'raised', 'raise']):
        print("LIKELY SUBSTANTIVE (has metrics/actions)")
    else:
        print("(need manual judgment)")
    print()

print(f"\nScenario B: sonnet_balanced AGREES WITH MAJORITY, but other judges alone")
# Skeptic/Haiku say substantive, balanced says boilerplate
skeptic_alone_sub = two_v_one[
    (two_v_one["sonnet_balanced__label"] == "boilerplate") &
    (two_v_one["sonnet_skeptic__label"] == "substantive") &
    (two_v_one["haiku_pattern__label"] == "substantive")
]
print(f"  (Both skeptic & haiku say SUBSTANTIVE, balanced says BOILERPLATE)")
print(f"  → {len(skeptic_alone_sub)} cases")

print("\n" + "="*100)
print("KEY ISSUE: Scenario A cases are labeled BOILERPLATE by majority,")
print("but sonnet_balanced (the balanced arbiter) says SUBSTANTIVE.")
print("These deserve manual override if they actually contain material info.")
print("="*100)

====================================================================================================
DETAILED AUDIT: Let's read these sentences ourselves and see if majority votes are wrong
====================================================================================================

Analyzing 52 cases where 2 judges agreed, 1 dissented

Scenario A: sonnet_balanced says SUBSTANTIVE, other two say BOILERPLATE → labeled 'boilerplate'
  → 24 cases

  1. "As LLMs continue to improve, it only further accelerates the value realization and therefore, t..."
     → My read: (need manual judgment)

  2. "The U.S. consumer dynamics remain remarkably consistent with prior quarters...."
     → My read: (need manual judgment)

  3. "As such, a one-size-fits-all approach will not work, and I can see clear opportunities to lever..."
     → My read: (need manual judgment)

  4. "But what you saw was an incredible leaning down of our operating expenses...."
     → My read: (need manual judgment)

  5. "Therefore, a new approach is necessary for them to keep driving the cost down...."
     → My read: (need manual judgment)


Scenario B: sonnet_balanced AGREES WITH MAJORITY, but other judges alone
  (Both skeptic & haiku say SUBSTANTIVE, balanced says BOILERPLATE)
  → 0 cases

====================================================================================================
KEY ISSUE: Scenario A cases are labeled BOILERPLATE by majority,
but sonnet_balanced (the balanced arbiter) says SUBSTANTIVE.
These deserve manual override if they actually contain material info.
====================================================================================================

In [115]:
# ---- AUTO-CORRECT: Identify problematic cases & suggest fixes ----
audit_path = REPORTS_DIR / "disagreement_audit.csv"
audit_raw = pd.read_csv(audit_path)

# The 24 problematic cases where sonnet_balanced says SUBSTANTIVE but majority says BOILERPLATE
problem_cases = audit_raw[
    (audit_raw["sonnet_balanced__label"] == "substantive") &
    (audit_raw["sonnet_skeptic__label"] == "boilerplate") &
    (audit_raw["haiku_pattern__label"] == "boilerplate")
].copy()

equals_100 = "="*100
print(f"\n{equals_100}")
print(f"MANUAL AUDIT OF {len(problem_cases)} PROBLEMATIC CASES")
print(f"{equals_100}\n")

fixes = []
for idx, row in problem_cases.iterrows():
    sent = row['sentence']
    
    # Apply rubric: SUBSTANTIVE if has specific numbers/metrics/named info
    # BOILERPLATE if vague strategy/pleasantries
    
    is_metrics = any(x in sent.lower() for x in [
        'revenue', 'grow', 'growth', 'margin', 'guidance', 'raise', 'raised', 
        '%', 'basis point', 'share', 'decline', 'increase', 'cost'
    ])
    
    # Contextual judgment
    if any(phrase in sent for phrase in [
        "As LLMs continue to improve",  # Generic product praise
        "one-size-fits-all approach",  # Generic strategy
        "opportunities to leverage"  # Generic strategy
    ]):
        my_judgment = "boilerplate"
    elif "consumer dynamics remain remarkably consistent" in sent:
        my_judgment = "substantive"  # Market commentary
    elif  "incredible leaning down" in sent or "cost down" in sent:
        my_judgment = "substantive"  # Specific cost action
    elif is_metrics:
        my_judgment = "substantive"
    else:
        my_judgment = "boilerplate"
    
    if my_judgment != row['gold_label']:
        fixes.append({
            'sentence_id': row['sentence_id'],
            'sentence': sent[:75],
            'original': row['gold_label'],
            'suggested': my_judgment
        })

print(f"Identified {len(fixes)} cases needing correction\n")
for i, fix in enumerate(fixes[:10], 1):
    print(f"{i}. {fix['sentence']}...")
    print(f"   {fix['original']} → {fix['suggested']}\n")

if len(fixes) > 10:
    print(f"   ... {len(fixes) - 10} more cases\n")

# Save corrected version
audit_corrected = audit_raw.copy()
for fix in fixes:
    audit_corrected.loc[audit_corrected['sentence_id'] == fix['sentence_id'], 'gold_label'] = fix['suggested']

corrected_path = REPORTS_DIR / "disagreement_audit_SUGGESTED_FIXES.csv"
audit_corrected.to_csv(corrected_path, index=False)
print(f"{equals_100}")
print(f"✅ Saved {len(fixes)} suggested fixes to: {corrected_path}")
print(f"   To apply: copy file over main audit, then re-run reload cell")
print(f"{equals_100}")

====================================================================================================
MANUAL AUDIT OF 24 PROBLEMATIC CASES
====================================================================================================

Identified 8 cases needing correction

1. The U.S. consumer dynamics remain remarkably consistent with prior quarters...
   boilerplate → substantive

2. But what you saw was an incredible leaning down of our operating expenses....
   boilerplate → substantive

3. Therefore, a new approach is necessary for them to keep driving the cost do...
   boilerplate → substantive

4. The final rule will have a significant impact on the growth and competitive...
   boilerplate → substantive

5. And do you think it leads to a market share shift faster than we were expec...
   boilerplate → substantive

6. And so when I think about the longer term, our goal is to return to sustain...
   boilerplate → substantive

7. And remind us again what the delta is in terms of cost structure, the margi...
   boilerplate → substantive

8. I think the rate and pace of growth will depend a little bit on the macro a...
   boilerplate → substantive

====================================================================================================
✅ Saved 8 suggested fixes to: /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/reports/disagreement_audit_SUGGESTED_FIXES.csv
   To apply: copy file over main audit, then re-run reload cell
====================================================================================================

## 4 · Stratified 60 / 20 / 20 split

The test split is **frozen**: nothing downstream touches it until the final test cell.

In [178]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    gold, test_size=0.40, stratify=gold["y"], random_state=SEED,
)
val_df, test_df = train_test_split(
    temp_df, test_size=0.50, stratify=temp_df["y"], random_state=SEED,
)
for name, d in (("train", train_df), ("val", val_df), ("test", test_df)):
    d.to_parquet(CACHE_DIR / f"split_{name}.parquet", index=False)
    pos = d["y"].mean()
    print(f"{name:5s}  n={len(d):4d}  substantive={pos:.3f}  boilerplate={1-pos:.3f}")

train  n=1200  substantive=0.460  boilerplate=0.540
val    n= 400  substantive=0.460  boilerplate=0.540
test   n= 400  substantive=0.460  boilerplate=0.540

## 5 · Feature engineering

Two families: ~30 hand-crafted regex flags + frozen MPNet embeddings (768-d). Embeddings are cached.

In [179]:
# ---- Regex feature pack -------------------------------------------------
FEATURE_PATTERNS = [
    # OPERATOR / HOUSEKEEPING (boilerplate signals)
    ("starts_with_operator", r"^\s*(operator|moderator)[\s:.,]"),
    ("mute_lines",           r"\b(lines? (have been|are) placed on mute|on mute|in listen[- ]only mode)\b"),
    ("queue_phrase",         r"\b(press\s*\*?\s*[1-9]|press star|in the queue|withdraw your question|ask a question)\b"),
    ("recording_phrase",     r"\b(call is being recorded|today's call is being recorded)\b"),

    # WELCOME / CLOSING
    ("welcome_phrase",       r"\b(welcome to (the|today's|our)|good (morning|afternoon|evening),?\s*(everyone|all|ladies))"),
    ("conclude_phrase",      r"\b(this concludes|thank you for (joining|participating)|that concludes our call)"),
    ("turn_call_over",       r"\b(turn (the call|it) (over|back) to|hand (it|the call) (over|back) to)"),

    # SAFE HARBOR / FORWARD LOOKING
    ("forward_looking",      r"\bforward[- ]looking statements?\b"),
    ("safe_harbor",          r"\b(safe harbor|private securities litigation reform act|may differ materially|risks and uncertainties)\b"),
    ("non_gaap",             r"\b(non[- ]?gaap|gaap (to|and non)|reconciliation (of|to) gaap)\b"),
    ("sec_filings",          r"\b(10[- ]?[KQ]|sec (filings?|filing)|annual report|proxy statement)\b"),

    # Q&A PLEASANTRIES
    ("thanks_for_question",  r"\b(thanks?|thank you)( so much)?( ,)? for (taking|having|the question|joining)"),
    ("generic_greeting",     r"^\s*(hi|hey|hello|good (morning|afternoon|evening))[, ]"),
    ("name_intro",           r"\bthis is \w+ (from|at|with|on for)\s+[A-Z]\w+"),
    ("analyst_firm",         r"\b(goldman( sachs)?|jp\s*morgan|morgan stanley|wells fargo|bank of america|citi(group)?|barclays|deutsche|ubs|credit suisse|jefferies|cowen|raymond james|piper sandler|wedbush|kbw|stifel|baird|evercore|guggenheim|bernstein|oppenheimer|truist|td (cowen|securities))\b"),

    # MATERIAL CONTENT (substantive signals)
    ("has_dollar",           r"\$\s?\d"),
    ("has_percent",          r"\d+(\.\d+)?\s?%|\bpercent\b"),
    ("has_bps",              r"\bbasis points?\b|\bbps\b"),
    ("has_million_billion",  r"\b(million|billion|trillion|mn|bn)\b"),
    ("has_year",             r"\b(20[12]\d|fiscal\s+\d{4}|fy\s?\d{4})\b"),
    ("has_quarter",          r"\b(q[1-4]\b|first quarter|second quarter|third quarter|fourth quarter|fy\d+q\d)\b"),

    # GUIDANCE / STRATEGY
    ("guidance_word",        r"\b(guidance|guide|outlook|expect|anticipate|forecast|raise|raising|raised|reaffirm|reiterate)\b"),
    ("segment_word",         r"\b(segment|division|business unit|product line|geography|vertical|category)\b"),
    ("margin_word",          r"\b(margin|operating income|gross margin|EBITDA|free cash flow|FCF|EPS|earnings per share)\b"),
]

_COMPILED = [(name, re.compile(pat, re.IGNORECASE)) for name, pat in FEATURE_PATTERNS]


def regex_features(sentence: str) -> dict:
    s = sentence
    feats = {name: int(bool(rx.search(s))) for name, rx in _COMPILED}

    # Lexical / structural (continuous)
    n_chars = len(s)
    words = s.split()
    n_words = len(words)
    n_digits = sum(c.isdigit() for c in s)
    n_alpha  = sum(c.isalpha() for c in s)
    n_upper  = sum(c.isupper() for c in s)

    feats.update({
        "len_chars":      n_chars,
        "len_words":      n_words,
        "digit_ratio":    n_digits / max(1, n_chars),
        "uppercase_ratio": n_upper / max(1, n_alpha),
        "ends_with_question": int(s.rstrip().endswith("?")),
        "starts_with_number": int(bool(re.match(r"^\s*\d", s))),
        "first_person_count": sum(1 for w in words if w.lower() in {"we", "our", "us", "i"}),
        "modal_count":     sum(1 for w in words if w.lower() in
                               {"will", "would", "expect", "expects", "expected",
                                "plan", "plans", "intend", "may", "might", "could", "should"}),
        "proper_noun_run": int(bool(re.search(r"\b([A-Z][a-z]+\s+){2,}", s))),
    })
    return feats


REGEX_FEATURE_NAMES = list(regex_features("placeholder").keys())
print(f"{len(REGEX_FEATURE_NAMES)} regex features:")
print(", ".join(REGEX_FEATURE_NAMES))

33 regex features:
starts_with_operator, mute_lines, queue_phrase, recording_phrase, welcome_phrase, conclude_phrase, turn_call_over, forward_looking, safe_harbor, non_gaap, sec_filings, thanks_for_question, generic_greeting, name_intro, analyst_firm, has_dollar, has_percent, has_bps, has_million_billion, has_year, has_quarter, guidance_word, segment_word, margin_word, len_chars, len_words, digit_ratio, uppercase_ratio, ends_with_question, starts_with_number, first_person_count, modal_count, proper_noun_run

In [180]:
# ---- Build regex feature matrices for all three splits -------------------
def regex_matrix(df: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame([regex_features(s) for s in df["sentence"]],
                        index=df.index, columns=REGEX_FEATURE_NAMES)

X_train_rx = regex_matrix(train_df)
X_val_rx   = regex_matrix(val_df)
X_test_rx  = regex_matrix(test_df)
y_train = train_df["y"].values
y_val   = val_df["y"].values
y_test  = test_df["y"].values

print("Regex matrix shapes:",
      X_train_rx.shape, X_val_rx.shape, X_test_rx.shape)

Regex matrix shapes: (1200, 33) (400, 33) (400, 33)

In [181]:
# ---- Frozen sentence embeddings ----------------------------------------
EMBED_CACHE = CACHE_DIR / f"embeddings_{EMBED_MODEL_NAME.replace('/', '__')}.npz"

def embed_sentences(sentences: list[str]) -> np.ndarray:
    from sentence_transformers import SentenceTransformer
    model = SentenceTransformer(EMBED_MODEL_NAME)
    return model.encode(sentences, batch_size=64, show_progress_bar=True,
                        convert_to_numpy=True, normalize_embeddings=True)


if EMBED_CACHE.exists():
    cache = np.load(EMBED_CACHE, allow_pickle=True)
    cached_ids = set(cache["sentence_ids"].tolist())
    cached_emb = {sid: cache["embeddings"][i] for i, sid in enumerate(cache["sentence_ids"])}
else:
    cached_ids, cached_emb = set(), {}

needed_df = gold[~gold["sentence_id"].isin(cached_ids)]
if len(needed_df):
    print(f"Embedding {len(needed_df):,} new sentences...")
    new_emb = embed_sentences(needed_df["sentence"].tolist())
    for sid, emb in zip(needed_df["sentence_id"], new_emb):
        cached_emb[sid] = emb
    sids = np.array(list(cached_emb.keys()))
    embs = np.stack([cached_emb[sid] for sid in sids])
    np.savez_compressed(EMBED_CACHE, sentence_ids=sids, embeddings=embs)

def get_emb(df: pd.DataFrame) -> np.ndarray:
    return np.stack([cached_emb[sid] for sid in df["sentence_id"]])

X_train_emb = get_emb(train_df)
X_val_emb   = get_emb(val_df)
X_test_emb  = get_emb(test_df)

X_train_full = np.hstack([X_train_emb, X_train_rx.values])
X_val_full   = np.hstack([X_val_emb,   X_val_rx.values])
X_test_full  = np.hstack([X_test_emb,  X_test_rx.values])

print("Embedding shapes:", X_train_emb.shape, X_val_emb.shape, X_test_emb.shape)
print("Combined  shapes:", X_train_full.shape, X_val_full.shape, X_test_full.shape)

Embedding shapes: (1200, 768) (400, 768) (400, 768)
Combined  shapes: (1200, 801) (400, 801) (400, 801)

## 6 · Classifier zoo (12 entries, 7 families)

Each entry stores its 5-fold OOF probabilities (used for threshold tuning) and held-out test probabilities (used for the leaderboard).

| # | Family | Entry |
|---|---|---|
| 1 | Rules | Regex-feature majority vote |
| 2 | Linear | LogReg on MPNet embeddings |
| 3 | Linear (lexical) | Linear SVM on TF-IDF char n-grams (calibrated) |
| 4 | Tree | HistGradientBoosting on (embeddings ⊕ regex) |
| 5 | n-gram | FastText supervised |
| 6 | Contrastive | SetFit on MPNet |
| 7 | Transformer | FinBERT fine-tuned |
| 8 | Anchor (creative) | Prototype-cosine classifier |
| 9 | Hybrid (creative) | Two-stage triage (rules → embedding LogReg) |
| 10 | Distillation (creative) | Soft-label LogReg trained on mean-judge probability |
| 11 | Ensemble | Mean-probability of top-5 non-transformer |
| 12 | Ensemble | Stacked meta-LogReg on OOF probabilities |

Entries 8, 9, 10, 12 are the creative additions. Each cell is self-contained: re-run any single one without touching the others.

In [131]:
# ---- Shared infrastructure ----------------------------------------------
from sklearn.metrics import (precision_recall_fscore_support, confusion_matrix,
                             classification_report, f1_score, recall_score)
from sklearn.model_selection import StratifiedKFold


@dataclass
class Entry:
    name: str
    family: str
    description: str
    train_seconds: float = 0.0
    sentences_per_second: float = 0.0
    oof_proba: np.ndarray = field(default_factory=lambda: np.zeros(0))
    test_proba: np.ndarray = field(default_factory=lambda: np.zeros(0))
    notes: str = ""


# Train+val pool for OOF threshold tuning
X_pool_emb  = np.vstack([X_train_emb,  X_val_emb])
X_pool_rx   = pd.concat([X_train_rx, X_val_rx]).reset_index(drop=True)
X_pool_full = np.vstack([X_train_full, X_val_full])
y_pool      = np.concatenate([y_train, y_val])
df_pool     = pd.concat([train_df, val_df]).reset_index(drop=True)

print("Pool size:", len(y_pool), "  test size:", len(y_test))

ENTRIES: dict[str, Entry] = {}

def cv_indices():
    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
    return list(skf.split(X_pool_emb, y_pool))


def time_inference(predict_fn, X) -> float:
    """Return sentences/second (rough — wall-clock, single thread)."""
    t0 = time.perf_counter()
    predict_fn(X)
    elapsed = time.perf_counter() - t0
    return len(X) / max(elapsed, 1e-9)

Pool size: 1600   test size: 400

In [182]:
# Entry 1 — Rules-only baseline (no learning, threshold via signal-count) -----
def rules_score(rx_df: pd.DataFrame) -> np.ndarray:
    """Score = sigmoid( substantive_signals - boilerplate_signals ). Higher → substantive."""
    boilerplate_keys = ["starts_with_operator", "mute_lines", "queue_phrase",
                        "recording_phrase", "welcome_phrase", "conclude_phrase",
                        "turn_call_over", "forward_looking", "safe_harbor",
                        "thanks_for_question", "generic_greeting", "name_intro",
                        "analyst_firm"]
    substantive_keys = ["has_dollar", "has_percent", "has_bps",
                        "has_million_billion", "has_year", "has_quarter",
                        "guidance_word", "segment_word", "margin_word"]
    boi = rx_df[boilerplate_keys].sum(axis=1).values
    sub = rx_df[substantive_keys].sum(axis=1).values
    z = sub.astype(float) - boi.astype(float)
    return 1.0 / (1.0 + np.exp(-z))                        # sigmoid


t0 = time.perf_counter()
oof = rules_score(X_pool_rx)
t_train = time.perf_counter() - t0

t0 = time.perf_counter()
test_p = rules_score(X_test_rx)
t_pred = time.perf_counter() - t0

ENTRIES["rules_only"] = Entry(
    name="rules_only", family="Rules",
    description="Regex feature signal-count → sigmoid",
    train_seconds=t_train, sentences_per_second=len(X_test_rx) / max(t_pred, 1e-9),
    oof_proba=oof, test_proba=test_p,
    notes="Zero learning. Bound by feature coverage.",
)
print("rules_only OK:", oof.shape, test_p.shape)

rules_only OK: (1600,) (400,)

In [183]:
# Entry 2 — LogReg on MPNet embeddings -------------------------------------
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline


def make_logreg_emb():
    return Pipeline([
        ("scaler", StandardScaler(with_mean=False)),
        ("clf", LogisticRegression(max_iter=2000, C=1.0, class_weight="balanced",
                                   random_state=SEED)),
    ])


oof = np.zeros(len(y_pool))
t0 = time.perf_counter()
for tr, te in cv_indices():
    m = make_logreg_emb()
    m.fit(X_pool_emb[tr], y_pool[tr])
    oof[te] = m.predict_proba(X_pool_emb[te])[:, 1]
t_train = time.perf_counter() - t0

final = make_logreg_emb().fit(X_pool_emb, y_pool)
sps = time_inference(lambda X: final.predict_proba(X), X_test_emb)
test_p = final.predict_proba(X_test_emb)[:, 1]

ENTRIES["logreg_embed"] = Entry(
    name="logreg_embed", family="Linear",
    description="LogReg on frozen MPNet embeddings (class-weighted)",
    train_seconds=t_train, sentences_per_second=sps,
    oof_proba=oof, test_proba=test_p,
)
print("logreg_embed OK")

logreg_embed OK

In [184]:
# Entry 3 — Linear SVM (calibrated) on TF-IDF char n-grams -----------------
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV


def make_svm_tfidf():
    return Pipeline([
        ("tfidf", TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5),
                                  min_df=2, sublinear_tf=True)),
        ("clf", CalibratedClassifierCV(LinearSVC(C=1.0, class_weight="balanced",
                                                 random_state=SEED),
                                       method="sigmoid", cv=3)),
    ])


texts_pool = pd.concat([train_df, val_df])["sentence"].tolist()
texts_test = test_df["sentence"].tolist()

oof = np.zeros(len(y_pool))
t0 = time.perf_counter()
for tr, te in cv_indices():
    m = make_svm_tfidf()
    m.fit([texts_pool[i] for i in tr], y_pool[tr])
    oof[te] = m.predict_proba([texts_pool[i] for i in te])[:, 1]
t_train = time.perf_counter() - t0

final = make_svm_tfidf().fit(texts_pool, y_pool)
sps = time_inference(lambda X: final.predict_proba(X), texts_test)
test_p = final.predict_proba(texts_test)[:, 1]

ENTRIES["svm_charngram"] = Entry(
    name="svm_charngram", family="Linear (lexical)",
    description="Linear SVM on char 3–5 n-grams, sigmoid-calibrated",
    train_seconds=t_train, sentences_per_second=sps,
    oof_proba=oof, test_proba=test_p,
    notes="Different feature space than embeddings — useful ensemble member.",
)
print("svm_charngram OK")

svm_charngram OK

In [185]:
# Entry 4 — HistGradientBoosting on (embeddings + regex flags) -------------
from sklearn.ensemble import HistGradientBoostingClassifier


def make_hgb():
    return HistGradientBoostingClassifier(
        max_iter=400, learning_rate=0.07, max_depth=6,
        min_samples_leaf=20, random_state=SEED, class_weight="balanced",
    )


oof = np.zeros(len(y_pool))
t0 = time.perf_counter()
for tr, te in cv_indices():
    m = make_hgb()
    m.fit(X_pool_full[tr], y_pool[tr])
    oof[te] = m.predict_proba(X_pool_full[te])[:, 1]
t_train = time.perf_counter() - t0

final = make_hgb().fit(X_pool_full, y_pool)
sps = time_inference(lambda X: final.predict_proba(X), X_test_full)
test_p = final.predict_proba(X_test_full)[:, 1]

ENTRIES["hgb_combined"] = Entry(
    name="hgb_combined", family="Tree ensemble",
    description="HistGradientBoosting on (embeddings ⊕ 30 regex flags)",
    train_seconds=t_train, sentences_per_second=sps,
    oof_proba=oof, test_proba=test_p,
)
print("hgb_combined OK")

hgb_combined OK

In [63]:
pip install fasttext-wheel

Requirement already satisfied: fasttext-wheel in /opt/homebrew/lib/python3.11/site-packages (0.9.2)
Requirement already satisfied: pybind11>=2.2 in /opt/homebrew/lib/python3.11/site-packages (from fasttext-wheel) (3.0.4)
Requirement already satisfied: setuptools>=0.7.0 in /opt/homebrew/lib/python3.11/site-packages (from fasttext-wheel) (80.10.2)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.11/site-packages (from fasttext-wheel) (2.4.2)

[notice] A new release of pip is available: 26.0 -> 26.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [186]:
# Entry 5 — FastText (supervised) ------------------------------------------
try:
    import fasttext
    HAS_FASTTEXT = True
except Exception:
    HAS_FASTTEXT = False
    print("fasttext not installed — skipping. `pip install fasttext-wheel` to enable.")


if HAS_FASTTEXT:
    def to_ft_lines(texts, labels):
        return [f"__label__{l} {t.replace(chr(10), ' ')}\n" for t, l in zip(texts, labels)]

    def train_ft(texts, labels, path: Path):
        path.write_text("".join(to_ft_lines(texts, labels)))
        return fasttext.train_supervised(
            input=str(path), lr=0.5, epoch=25, wordNgrams=2,
            dim=100, minCount=1, loss="softmax", verbose=0,
        )

    def ft_proba(model, texts) -> np.ndarray:
        out = np.zeros(len(texts))
        for i, t in enumerate(texts):
            clean = t.replace("\n", " ")
            # fasttext's Python wrapper calls np.array(..., copy=False), which
            # breaks under NumPy 2.x. The pybind method returns plain tuples.
            pred = model.f.predict(clean, 2, 0.0, "strict")
            for p, label in pred:
                if label.endswith("__1"):
                    out[i] = float(p)
        return out

    oof = np.zeros(len(y_pool))
    ft_train_path = CACHE_DIR / "ft_train.txt"
    t0 = time.perf_counter()
    for fold, (tr, te) in enumerate(cv_indices()):
        m = train_ft([texts_pool[i] for i in tr], y_pool[tr], ft_train_path)
        oof[te] = ft_proba(m, [texts_pool[i] for i in te])
    t_train = time.perf_counter() - t0

    final = train_ft(texts_pool, y_pool, ft_train_path)
    sps = time_inference(lambda X: ft_proba(final, X), texts_test)
    test_p = ft_proba(final, texts_test)

    ENTRIES["fasttext"] = Entry(
        name="fasttext", family="N-gram",
        description="FastText supervised, wordNgrams=2, dim=100, 25 epochs",
        train_seconds=t_train, sentences_per_second=sps,
        oof_proba=oof, test_proba=test_p,
    )
    print("fasttext OK")

fasttext OK

In [187]:
# Entry 6 — SetFit (contrastive fine-tuning) -------------------------------
# Compatibility guard: if the live kernel imported Homebrew transformers 5.x
# before we installed the compatible user-site 4.x package, clear the stale
# modules and put the user site first. This avoids a full rerun of prior cells.
import importlib, site, sys, warnings
warnings.filterwarnings("ignore", category=DeprecationWarning, module=r"sentence_transformers\.cross_encoder.*")

_user_site = site.getusersitepackages()
if _user_site in sys.path:
    sys.path.remove(_user_site)
sys.path.insert(0, _user_site)
for _mod in list(sys.modules):
    if (_mod == "transformers" or _mod.startswith("transformers.")
            or _mod == "sentence_transformers" or _mod.startswith("sentence_transformers.")
            or _mod == "setfit" or _mod.startswith("setfit.")):
        del sys.modules[_mod]
importlib.invalidate_caches()

if ENABLE_SETFIT:
    try:
        from setfit import SetFitModel, Trainer, TrainingArguments
        from datasets import Dataset
        HAS_SETFIT = True
    except Exception as e:
        HAS_SETFIT = False
        print("SetFit not available:", e)

    if HAS_SETFIT:
        def make_setfit():
            return SetFitModel.from_pretrained(EMBED_MODEL_NAME)

        SETFIT_NUM_ITERATIONS = 4
        SETFIT_MAX_STEPS = 80

        def fit_setfit(texts, labels, run_name="setfit"):
            ds = Dataset.from_dict({"text": list(texts), "label": list(labels)})
            model = make_setfit()
            args = TrainingArguments(
                batch_size=8,
                num_iterations=SETFIT_NUM_ITERATIONS,
                num_epochs=1,
                max_steps=SETFIT_MAX_STEPS,
                output_dir=str(CACHE_DIR / "setfit_out" / run_name),
                report_to="none",
                save_strategy="no",
                show_progress_bar=False,
            )
            Trainer(model=model, args=args, train_dataset=ds).train()
            return model

        oof = np.zeros(len(y_pool))
        t0 = time.perf_counter()
        for fold, (tr, te) in enumerate(cv_indices()):
            print(f"SetFit fold {fold + 1}/{N_FOLDS}...")
            m = fit_setfit([texts_pool[i] for i in tr], y_pool[tr], run_name=f"fold_{fold}")
            probs = np.asarray(m.predict_proba([texts_pool[i] for i in te]))
            oof[te] = (probs[:, 1] if probs.ndim == 2 and probs.shape[1] == 2
                       else probs.reshape(-1))
            del m
        t_train = time.perf_counter() - t0

        print("SetFit final fit...")
        final = fit_setfit(texts_pool, y_pool, run_name="final")
        SETFIT_FINAL = final
        SETFIT_MODEL_DIR = MODELS_DIR / "setfit_final"
        final.save_pretrained(str(SETFIT_MODEL_DIR))
        def setfit_predict(X):
            p = np.asarray(final.predict_proba(list(X)))
            return p[:, 1] if p.ndim == 2 and p.shape[1] == 2 else p.reshape(-1)
        sps = time_inference(setfit_predict, texts_test)
        test_p = setfit_predict(texts_test)

        ENTRIES["setfit"] = Entry(
            name="setfit", family="Contrastive",
            description=f"SetFit on MPNet, {SETFIT_NUM_ITERATIONS} iterations, max {SETFIT_MAX_STEPS} steps",
            train_seconds=t_train, sentences_per_second=sps,
            oof_proba=oof, test_proba=test_p,
            notes="Often the strongest single model for small labeled sets.",
        )
        print("setfit OK")

SetFit fold 1/5...

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Map: 100%|██████████| 1280/1280 [00:00<00:00, 33832.07 examples/s]
***** Running training *****
***** Running training *****
***** Running training *****
  Num unique pairs = 10240
  Num unique pairs = 10240
  Num unique pairs = 10240
  Batch size = 8
  Batch size = 8
  Batch size = 8
  Num epochs = 1
  Num epochs = 1
  Num epochs = 1

SetFit fold 2/5...

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Map: 100%|██████████| 1280/1280 [00:00<00:00, 44115.02 examples/s]
***** Running training *****
***** Running training *****
***** Running training *****
  Num unique pairs = 10240
  Num unique pairs = 10240
  Num unique pairs = 10240
  Batch size = 8
  Batch size = 8
  Batch size = 8
  Num epochs = 1
  Num epochs = 1
  Num epochs = 1

SetFit fold 3/5...

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Map: 100%|██████████| 1280/1280 [00:00<00:00, 44819.54 examples/s]
***** Running training *****
***** Running training *****
***** Running training *****
  Num unique pairs = 10240
  Num unique pairs = 10240
  Num unique pairs = 10240
  Batch size = 8
  Batch size = 8
  Batch size = 8
  Num epochs = 1
  Num epochs = 1
  Num epochs = 1

SetFit fold 4/5...

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Map: 100%|██████████| 1280/1280 [00:00<00:00, 47079.49 examples/s]
***** Running training *****
***** Running training *****
***** Running training *****
  Num unique pairs = 10240
  Num unique pairs = 10240
  Num unique pairs = 10240
  Batch size = 8
  Batch size = 8
  Batch size = 8
  Num epochs = 1
  Num epochs = 1
  Num epochs = 1

SetFit fold 5/5...

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Map: 100%|██████████| 1280/1280 [00:00<00:00, 48127.41 examples/s]
***** Running training *****
***** Running training *****
***** Running training *****
  Num unique pairs = 10240
  Num unique pairs = 10240
  Num unique pairs = 10240
  Batch size = 8
  Batch size = 8
  Batch size = 8
  Num epochs = 1
  Num epochs = 1
  Num epochs = 1

SetFit final fit...

model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
model_head.pkl not found on HuggingFace Hub, initialising classification head with random weights. You should TRAIN this model on a downstream task to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Map: 100%|██████████| 1600/1600 [00:00<00:00, 51420.48 examples/s]
***** Running training *****
***** Running training *****
***** Running training *****
  Num unique pairs = 12800
  Num unique pairs = 12800
  Num unique pairs = 12800
  Batch size = 8
  Batch size = 8
  Batch size = 8
  Num epochs = 1
  Num epochs = 1
  Num epochs = 1

setfit OK

In [76]:
# One-time compatibility fix for SetFit API expectations
import subprocess, sys
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', 'sentence-transformers==2.7.0'], check=True)
print('Installed sentence-transformers==2.7.0; rerun SetFit cell next.')

Python(46798) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Installed sentence-transformers==2.7.0; rerun SetFit cell next.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
setfit 1.1.3 requires sentence-transformers[train]>=3, but you have sentence-transformers 2.7.0 which is incompatible.

[notice] A new release of pip is available: 26.0 -> 26.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip

In [77]:
# Retry with SetFit-compatible sentence-transformers 3.x
import subprocess, sys
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', 'sentence-transformers==3.0.1'], check=True)
print('Installed sentence-transformers==3.0.1')

Python(46799) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Installed sentence-transformers==3.0.1

[notice] A new release of pip is available: 26.0 -> 26.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip

In [65]:
# Entry 7 — FinBERT fine-tuned ---------------------------------------------
if ENABLE_FINBERT:
    try:
        import torch
        from transformers import (BertTokenizerFast, AutoModelForSequenceClassification,
                                  TrainingArguments as HFArgs, Trainer as HFTrainer)
        from datasets import Dataset
        HAS_HF = True
    except Exception as e:
        HAS_HF = False
        print("transformers not available:", e)

    if HAS_HF:
        FINBERT_BASE = "yiyanghkust/finbert-tone"
        DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

        def fit_finbert(texts, labels, output_dir: Path):
            tok = BertTokenizerFast.from_pretrained(FINBERT_BASE)
            model = AutoModelForSequenceClassification.from_pretrained(
                FINBERT_BASE, num_labels=2, ignore_mismatched_sizes=True,
            ).to(DEVICE)

            def tok_fn(batch):
                return tok(batch["text"], truncation=True, padding="max_length", max_length=96)

            ds = (Dataset.from_dict({"text": list(texts), "label": list(labels)})
                          .map(tok_fn, batched=True))
            ds = ds.remove_columns(["text"])
            ds.set_format("torch")

            args = HFArgs(
                output_dir=str(output_dir), num_train_epochs=3,
                per_device_train_batch_size=16, learning_rate=2e-5,
                logging_steps=50, save_strategy="no", report_to="none",
                seed=SEED, dataloader_num_workers=0,
            )
            HFTrainer(model=model, args=args, train_dataset=ds).train()
            return model, tok

        @torch.no_grad()
        def finbert_proba(model, tok, texts) -> np.ndarray:
            model.eval()
            out = []
            BS = 32
            for i in range(0, len(texts), BS):
                batch = list(texts[i:i + BS])
                enc = tok(batch, return_tensors="pt", truncation=True,
                          padding=True, max_length=96).to(DEVICE)
                logits = model(**enc).logits
                p = torch.softmax(logits, dim=-1)[:, 1].cpu().numpy()
                out.extend(p.tolist())
            return np.asarray(out)

        oof = np.zeros(len(y_pool))
        t0 = time.perf_counter()
        for fold, (tr, te) in enumerate(cv_indices()):
            m, tk = fit_finbert([texts_pool[i] for i in tr], y_pool[tr],
                                CACHE_DIR / f"finbert_fold{fold}")
            oof[te] = finbert_proba(m, tk, [texts_pool[i] for i in te])
            del m, tk
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        t_train = time.perf_counter() - t0

        m_final, tk_final = fit_finbert(texts_pool, y_pool, CACHE_DIR / "finbert_full")
        sps = time_inference(lambda X: finbert_proba(m_final, tk_final, X), texts_test)
        test_p = finbert_proba(m_final, tk_final, texts_test)

        ENTRIES["finbert"] = Entry(
            name="finbert", family="Transformer",
            description="FinBERT (yiyanghkust/finbert-tone) fine-tuned, 3 epochs LR 2e-5",
            train_seconds=t_train, sentences_per_second=sps,
            oof_proba=oof, test_proba=test_p,
        )
        print("finbert OK")

In [188]:
# Entry 8 — Prototype-cosine classifier (creative, zero-training) ----------
# For each class, we keep K=24 anchor sentences with the highest mean within-class
# similarity (the "prototypes"). At inference we score by max cosine similarity to
# either set, then turn the gap into a probability via a sigmoid.
def select_prototypes(emb: np.ndarray, k: int = 24) -> np.ndarray:
    """Greedy k-medoids-style: pick the k sentences with the highest sum of
    cosine similarity to all other sentences in the class."""
    sims = emb @ emb.T                           # cosine (already normalized)
    centrality = sims.sum(axis=1)
    return np.argsort(-centrality)[:k]


t0 = time.perf_counter()
proto_idx_pos = select_prototypes(X_pool_emb[y_pool == 1])
proto_idx_neg = select_prototypes(X_pool_emb[y_pool == 0])
proto_pos = X_pool_emb[y_pool == 1][proto_idx_pos]
proto_neg = X_pool_emb[y_pool == 0][proto_idx_neg]
t_train = time.perf_counter() - t0


def proto_score(X: np.ndarray) -> np.ndarray:
    s_pos = (X @ proto_pos.T).max(axis=1)
    s_neg = (X @ proto_neg.T).max(axis=1)
    z = (s_pos - s_neg) * 8.0                    # temperature
    return 1.0 / (1.0 + np.exp(-z))


def proto_oof(X_full, y, splits):
    oof = np.zeros(len(y))
    for tr, te in splits:
        Xtr, ytr = X_full[tr], y[tr]
        idx_pos = select_prototypes(Xtr[ytr == 1])
        idx_neg = select_prototypes(Xtr[ytr == 0])
        Pp, Pn = Xtr[ytr == 1][idx_pos], Xtr[ytr == 0][idx_neg]
        s_pos = (X_full[te] @ Pp.T).max(axis=1)
        s_neg = (X_full[te] @ Pn.T).max(axis=1)
        oof[te] = 1.0 / (1.0 + np.exp(-(s_pos - s_neg) * 8.0))
    return oof


oof = proto_oof(X_pool_emb, y_pool, cv_indices())
sps = time_inference(proto_score, X_test_emb)
test_p = proto_score(X_test_emb)

ENTRIES["prototype_cosine"] = Entry(
    name="prototype_cosine", family="Anchor (creative)",
    description="K-medoid prototypes per class; max-cosine gap → sigmoid",
    train_seconds=t_train, sentences_per_second=sps,
    oof_proba=oof, test_proba=test_p,
    notes="No gradient descent. Interpretable: which prototype was closest?",
)
print("prototype_cosine OK")

prototype_cosine OK

In [189]:
# Entry 9 — Two-stage triage (creative) -----------------------------------
# Stage 1: strong rule signals decide obvious cases (very high precision flags only).
# Stage 2: the embedding LogReg classifies the rest.
#
# Goal: push substantive recall up by NEVER calling a sentence boilerplate that
# contains a hard substantive cue ($, %, bps, guidance verb), regardless of what
# the model thinks.
HARD_SUB_KEYS = ["has_dollar", "has_percent", "has_bps", "has_million_billion",
                 "has_year", "has_quarter", "guidance_word", "margin_word"]
HARD_BOI_KEYS = ["starts_with_operator", "mute_lines", "queue_phrase",
                 "recording_phrase", "safe_harbor", "forward_looking",
                 "name_intro", "analyst_firm"]


def two_stage_score(rx_df: pd.DataFrame, emb: np.ndarray, base_model) -> np.ndarray:
    base_p = base_model.predict_proba(emb)[:, 1]
    sub_hits = rx_df[HARD_SUB_KEYS].sum(axis=1).values
    boi_hits = rx_df[HARD_BOI_KEYS].sum(axis=1).values
    out = base_p.copy()
    out = np.where(sub_hits >= 1, np.maximum(out, 0.92), out)   # force ≥ 0.92 if hard sub cue
    out = np.where((sub_hits == 0) & (boi_hits >= 2),
                   np.minimum(out, 0.10), out)                  # force ≤ 0.10 if 2+ boi cues and no sub cue
    return out


t0 = time.perf_counter()
oof = np.zeros(len(y_pool))
for tr, te in cv_indices():
    base = make_logreg_emb().fit(X_pool_emb[tr], y_pool[tr])
    oof[te] = two_stage_score(X_pool_rx.iloc[te], X_pool_emb[te], base)
t_train = time.perf_counter() - t0

base_full = make_logreg_emb().fit(X_pool_emb, y_pool)
def stage_predict(emb): return two_stage_score(X_test_rx, emb, base_full)
sps = time_inference(stage_predict, X_test_emb)
test_p = two_stage_score(X_test_rx, X_test_emb, base_full)

ENTRIES["two_stage"] = Entry(
    name="two_stage", family="Hybrid (creative)",
    description="Rule overrides on hard cues + LogReg(embeddings) for the rest",
    train_seconds=t_train, sentences_per_second=sps,
    oof_proba=oof, test_proba=test_p,
    notes="Designed for the recall floor — hard $%/bps cues never get downgraded.",
)
print("two_stage OK")

two_stage OK

In [190]:
# Entry 10 — Soft-label distillation LogReg (creative) ---------------------
# Use the mean of the three judges' P(substantive) as a SOFT TARGET. Train a
# regularized regression on embeddings; threshold its output as a probability.
# We weight each sample by judge agreement so noisy labels contribute less.
from sklearn.linear_model import Ridge

# Build mean-judge probability per sentence in the pool
votes_pool = votes_df[votes_df["sentence_id"].isin(df_pool["sentence_id"])].copy()
votes_pool["p_sub"] = np.where(votes_pool["label"] == "substantive",
                               votes_pool["confidence"],
                               1.0 - votes_pool["confidence"])
mean_p = votes_pool.groupby("sentence_id")["p_sub"].mean()
agree  = votes_pool.groupby("sentence_id")["label"].apply(
            lambda s: int(s.value_counts().iloc[0] == len(s)))   # 1 if unanimous

soft_target = df_pool["sentence_id"].map(mean_p).fillna(df_pool["y"]).values
sample_w    = 0.6 + 0.4 * df_pool["sentence_id"].map(agree).fillna(0.5).values  # ∈ [0.6, 1.0]


def make_distill():
    return Pipeline([
        ("scaler", StandardScaler(with_mean=False)),
        ("clf", Ridge(alpha=1.0, random_state=SEED)),
    ])


def to_proba(z):  # squash ridge output
    return 1.0 / (1.0 + np.exp(-(z * 4.0 - 2.0)))


oof = np.zeros(len(y_pool))
t0 = time.perf_counter()
for tr, te in cv_indices():
    m = make_distill()
    m.fit(X_pool_emb[tr], soft_target[tr], clf__sample_weight=sample_w[tr])
    oof[te] = to_proba(m.predict(X_pool_emb[te]))
t_train = time.perf_counter() - t0

final = make_distill().fit(X_pool_emb, soft_target, clf__sample_weight=sample_w)
def distill_predict(X): return to_proba(final.predict(X))
sps = time_inference(distill_predict, X_test_emb)
test_p = distill_predict(X_test_emb)

ENTRIES["distill_softlabel"] = Entry(
    name="distill_softlabel", family="Distillation (creative)",
    description="Ridge on embeddings, fit to mean-judge probability with agreement weights",
    train_seconds=t_train, sentences_per_second=sps,
    oof_proba=oof, test_proba=test_p,
    notes="Inference uses only embeddings — no LLM calls at deploy time.",
)
print("distill_softlabel OK")

distill_softlabel OK

In [170]:
# Entry 11 — Mean-probability ensemble of top-5 non-transformer ------------
def macro_f1_oof(entry: Entry, threshold: float = 0.5) -> float:
    return f1_score(y_pool, (entry.oof_proba >= threshold).astype(int), average="macro")


# Rank current entries by OOF macro-F1 at default threshold; pick top 5 non-transformer.
ranked = sorted([e for e in ENTRIES.values() if e.family != "Transformer"],
                key=macro_f1_oof, reverse=True)[:5]
print("Mean ensemble members:", [e.name for e in ranked])

mean_oof  = np.mean([e.oof_proba  for e in ranked], axis=0)
mean_test = np.mean([e.test_proba for e in ranked], axis=0)

ENTRIES["mean_ensemble"] = Entry(
    name="mean_ensemble", family="Ensemble",
    description=f"Mean-probability of top-5: {[e.name for e in ranked]}",
    train_seconds=sum(e.train_seconds for e in ranked),
    sentences_per_second=min(e.sentences_per_second for e in ranked),
    oof_proba=mean_oof, test_proba=mean_test,
    notes="Cheap to combine; usually 1–3 F1 points over the best single member.",
)
print("mean_ensemble OK")

Mean ensemble members: ['stacked_meta', 'recall_safe_blend', 'weighted_recall_ensemble_v2', 'optimized_ensemble', 'mean_ensemble']
mean_ensemble OK

In [142]:
# Entry 12 — Stacked meta-LogReg on OOF probabilities (creative) -----------
# Train a meta-classifier on the OOF probabilities of the same top-5 members.
# Because OOF probs are unbiased (each fold's prediction came from a model that
# didn't see the held-out points), this is honest stacking.
from sklearn.linear_model import LogisticRegression as LR

X_meta_pool = np.column_stack([e.oof_proba  for e in ranked])
X_meta_test = np.column_stack([e.test_proba for e in ranked])

t0 = time.perf_counter()
meta_oof = np.zeros(len(y_pool))
for tr, te in cv_indices():
    m = LR(max_iter=500, C=1.0).fit(X_meta_pool[tr], y_pool[tr])
    meta_oof[te] = m.predict_proba(X_meta_pool[te])[:, 1]
meta = LR(max_iter=500, C=1.0).fit(X_meta_pool, y_pool)
test_p = meta.predict_proba(X_meta_test)[:, 1]
t_train = time.perf_counter() - t0

ENTRIES["stacked_meta"] = Entry(
    name="stacked_meta", family="Ensemble",
    description=f"LogReg stacked on OOF probs of top-5: {[e.name for e in ranked]}",
    train_seconds=t_train,
    sentences_per_second=min(e.sentences_per_second for e in ranked),
    oof_proba=meta_oof, test_proba=test_p,
    notes="Learns weights instead of averaging. More flexible than mean ensemble.",
)
print("stacked_meta OK")
print("\\nAll entries:", list(ENTRIES))

stacked_meta OK
\nAll entries: ['rules_only', 'logreg_embed', 'svm_charngram', 'hgb_combined', 'fasttext', 'setfit', 'prototype_cosine', 'two_stage', 'distill_softlabel', 'mean_ensemble', 'stacked_meta']

## 7 · Recall-constrained threshold tuning

For each entry: sweep the decision threshold over `[0.05, 0.95]`, find the **largest** threshold satisfying substantive recall ≥ 0.96 on pooled OOF predictions, then among all feasible thresholds pick the one with maximum macro-F1.

Reports per-fold std of the optimal threshold (the handout asks for it). Entries that cannot meet the floor are flagged `INFEASIBLE` — we do **not** silently relax the constraint.

In [196]:
def per_fold_best_threshold(probs: np.ndarray, y: np.ndarray,
                            splits, recall_floor: float) -> tuple[float, float]:
    """Return (mean, std) of per-fold best thresholds that meet the floor.
    Returns (nan, nan) if no fold can meet the floor."""
    fold_thresholds = []
    grid = np.linspace(0.02, 0.98, 97)
    for _, te in splits:
        ys = y[te]; ps = probs[te]
        feasible = []
        for t in grid:
            yhat = (ps >= t).astype(int)
            if recall_score(ys, yhat, pos_label=1, zero_division=0) >= recall_floor:
                feasible.append((t, f1_score(ys, yhat, average="macro", zero_division=0)))
        if feasible:
            fold_thresholds.append(max(feasible, key=lambda x: x[1])[0])
    if not fold_thresholds:
        return float("nan"), float("nan")
    return float(np.mean(fold_thresholds)), float(np.std(fold_thresholds))


def tune_threshold(probs: np.ndarray, y: np.ndarray,
                   recall_floor: float = RECALL_FLOOR):
    grid = np.linspace(0.02, 0.98, 97)
    feasible = []
    for t in grid:
        yhat = (probs >= t).astype(int)
        if recall_score(y, yhat, pos_label=1, zero_division=0) >= recall_floor:
            feasible.append((t, f1_score(y, yhat, average="macro", zero_division=0)))
    if not feasible:
        return None, None, "INFEASIBLE"
    best_t, best_f1 = max(feasible, key=lambda x: x[1])
    return best_t, best_f1, "OK"


splits = cv_indices()
threshold_results = {}
for name, e in ENTRIES.items():
    best_t, best_f1, status = tune_threshold(e.oof_proba, y_pool, RECALL_FLOOR)
    fold_mean, fold_std = per_fold_best_threshold(e.oof_proba, y_pool, splits, RECALL_FLOOR)
    threshold_results[name] = {
        "threshold":      best_t,
        "oof_macroF1":    best_f1,
        "status":         status,
        "fold_mean":      fold_mean,
        "fold_std":       fold_std,
    }

pd.DataFrame(threshold_results).T.round(4)

,threshold,oof_macroF1,status,fold_mean,fold_std
rules_only,0.27,0.378903,OK,0.27,0.0
logreg_embed,None,None,INFEASIBLE,NaN,NaN
svm_charngram,0.44,0.343737,OK,0.358,0.169753
hgb_combined,None,None,INFEASIBLE,NaN,NaN
fasttext,None,None,INFEASIBLE,NaN,NaN
setfit,0.29,0.348576,OK,0.294,0.014967
prototype_cosine,0.32,0.597324,OK,0.328,0.022271
two_stage,None,None,INFEASIBLE,NaN,NaN
distill_softlabel,0.25,0.693026,OK,0.28,0.054037
mean_ensemble,0.24,0.822073,OK,0.244,0.053141
stacked_meta,0.14,0.815601,OK,0.146,0.045869
xgb_combined,0.05,0.757811,OK,0.07,0.028284
xgb_guarded,0.06,0.764021,OK,0.09,0.044721
weighted_recall_ensemble_v2,0.16,0.773968,OK,0.186,0.053141
logreg_embed_guarded,None,None,INFEASIBLE,NaN,NaN
hgb_combined_guarded,None,None,INFEASIBLE,NaN,NaN
lgb_combined,0.02,0.743744,OK,0.04,0.017321
optimized_ensemble,0.31,0.774639,OK,0.318,0.027129
recall_safe_blend,0.31,0.836863,OK,0.3,0.046043

## 8 · Held-out test evaluation and leaderboard

Apply each entry's tuned threshold to the **frozen** test set. Report test accuracy, macro-F1, per-class F1, training time, and approximate inference throughput. Sorted by macro-F1 descending, with infeasible entries listed at the bottom.

In [197]:
rows = []
for name, e in ENTRIES.items():
    tr = threshold_results[name]
    if tr["status"] == "INFEASIBLE":
        rows.append({
            "name": name, "family": e.family, "status": "INFEASIBLE",
            "threshold": np.nan, "test_acc": np.nan, "test_macroF1": np.nan,
            "boi_F1": np.nan, "sub_F1": np.nan, "sub_recall": np.nan, "sub_prec": np.nan,
            "train_sec": e.train_seconds, "sent_per_sec": e.sentences_per_second,
            "fold_threshold_std": tr["fold_std"], "description": e.description,
        })
        continue
    test_proba = np.asarray(e.test_proba).reshape(-1)
    yhat = (test_proba >= tr["threshold"]).astype(int)
    p, r, f, _ = precision_recall_fscore_support(y_test, yhat, labels=[0, 1], zero_division=0)
    rows.append({
        "name": name, "family": e.family, "status": "OK",
        "threshold": tr["threshold"],
        "test_acc": (yhat == y_test).mean(),
        "test_macroF1": f1_score(y_test, yhat, average="macro", zero_division=0),
        "boi_F1": f[0], "sub_F1": f[1], "sub_recall": r[1], "sub_prec": p[1],
        "train_sec": e.train_seconds, "sent_per_sec": e.sentences_per_second,
        "fold_threshold_std": tr["fold_std"], "description": e.description,
    })

LEADERBOARD = pd.DataFrame(rows)
LEADERBOARD["status_order"] = np.where(LEADERBOARD["status"] == "OK", 0, 1)
LEADERBOARD = (LEADERBOARD
               .sort_values(["status_order", "test_macroF1"], ascending=[True, False])
               .drop(columns=["status_order"])
               .reset_index(drop=True))
LEADERBOARD.to_csv(REPORTS_DIR / "leaderboard.csv", index=False)

display_cols = ["name", "family", "status", "threshold", "test_macroF1",
                "boi_F1", "sub_F1", "sub_recall", "sub_prec",
                "train_sec", "sent_per_sec", "fold_threshold_std"]
LEADERBOARD[display_cols].round(4)

,name,family,status,threshold,test_macroF1,boi_F1,sub_F1,sub_recall,sub_prec,train_sec,sent_per_sec,fold_threshold_std
0,xgb_combined,Boosted trees,OK,0.05,0.9325,0.9337,0.9313,0.9946,0.8756,45.2085,64401.8677,0.0283
1,lgb_combined,Gradient boosting,OK,0.02,0.9275,0.9284,0.9266,0.9946,0.8673,61.7892,49187.8895,0.0173
2,xgb_guarded,Hybrid (boosted + rules),OK,0.06,0.9125,0.9123,0.9127,0.9946,0.8433,45.2085,64401.8677,0.0447
3,weighted_recall_ensemble_v2,Ensemble,OK,0.16,0.8849,0.8808,0.8889,1.0000,0.8000,152.3213,18870.3723,0.0531
4,optimized_ensemble,Ensemble,OK,0.31,0.8620,0.8541,0.8700,1.0000,0.7699,478.4666,136.8373,0.0271
5,recall_safe_blend,Ensemble,OK,0.31,0.7696,0.7437,0.7955,0.9620,0.6782,1839.9424,123.0947,0.0460
6,mean_ensemble,Ensemble,OK,0.24,0.7565,0.7273,0.7857,0.9565,0.6667,1794.6607,123.0947,0.0531
7,stacked_meta,Ensemble,OK,0.14,0.7514,0.7216,0.7812,0.9511,0.6629,0.0140,123.0947,0.0459
8,distill_softlabel,Distillation (creative),OK,0.25,0.7176,0.6646,0.7705,0.9946,0.6289,0.0741,881785.6338,0.0540
9,prototype_cosine,Anchor (creative),OK,0.32,0.6247,0.5431,0.7064,0.9348,0.5677,0.0410,18870.3723,0.0223
10,rules_only,Rules,OK,0.27,0.3837,0.1217,0.6456,1.0000,0.4767,0.0731,140135.7568,0.0000
11,setfit,Contrastive,OK,0.29,0.3538,0.0711,0.6365,0.9946,0.4680,371.2807,136.8373,0.0150
12,svm_charngram,Linear (lexical),OK,0.44,0.3151,0.0000,0.6301,1.0000,0.4600,1.4099,8463.9142,0.1698
13,logreg_embed,Linear,INFEASIBLE,NaN,NaN,NaN,NaN,NaN,NaN,0.3944,26660.7409,NaN
14,hgb_combined,Tree ensemble,INFEASIBLE,NaN,NaN,NaN,NaN,NaN,NaN,40.9707,22510.5879,NaN
15,fasttext,N-gram,INFEASIBLE,NaN,NaN,NaN,NaN,NaN,NaN,4.1619,81228.5824,NaN
16,two_stage,Hybrid (creative),INFEASIBLE,NaN,NaN,NaN,NaN,NaN,NaN,0.1690,112209.8322,NaN
17,logreg_embed_guarded,Linear (guarded),INFEASIBLE,NaN,NaN,NaN,NaN,NaN,NaN,0.4370,590114.9813,NaN
18,hgb_combined_guarded,Tree ensemble (guarded),INFEASIBLE,NaN,NaN,NaN,NaN,NaN,NaN,41.6615,11929.9857,NaN

In [202]:
# ---- Leakage checks: split integrity + near-duplicate scan ------------------
from sklearn.feature_extraction.text import TfidfVectorizer


def _norm_text(s: str) -> str:
    s = str(s).lower()
    s = re.sub(r"\s+", " ", s).strip()
    s = re.sub(r"[^a-z0-9 %$.-]", "", s)
    return s


def _to_1d(x):
    if hasattr(x, "A1"):
        return x.A1
    if hasattr(x, "toarray"):
        return x.toarray().ravel()
    return np.asarray(x).ravel()


# Build split sets
train_ids = set(train_df["sentence_id"].astype(str))
val_ids = set(val_df["sentence_id"].astype(str))
test_ids = set(test_df["sentence_id"].astype(str))

train_text = set(train_df["sentence"].astype(str))
val_text = set(val_df["sentence"].astype(str))
test_text = set(test_df["sentence"].astype(str))

train_norm = set(train_df["sentence"].astype(str).map(_norm_text))
val_norm = set(val_df["sentence"].astype(str).map(_norm_text))
test_norm = set(test_df["sentence"].astype(str).map(_norm_text))

# Exact overlap checks
id_overlap_tv = len(train_ids & val_ids)
id_overlap_tt = len(train_ids & test_ids)
id_overlap_vt = len(val_ids & test_ids)

text_overlap_tv = len(train_text & val_text)
text_overlap_tt = len(train_text & test_text)
text_overlap_vt = len(val_text & test_text)

norm_overlap_tv = len(train_norm & val_norm)
norm_overlap_tt = len(train_norm & test_norm)
norm_overlap_vt = len(val_norm & test_norm)

# Near-duplicate scan (char n-gram TF-IDF cosine)
all_texts = pd.concat([
    train_df[["sentence_id", "sentence"]].assign(split="train"),
    val_df[["sentence_id", "sentence"]].assign(split="val"),
    test_df[["sentence_id", "sentence"]].assign(split="test"),
], ignore_index=True)
all_texts["norm_sentence"] = all_texts["sentence"].map(_norm_text)

vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5), min_df=1)
X = vec.fit_transform(all_texts["norm_sentence"])

idx_train = np.where(all_texts["split"].values == "train")[0]
idx_val = np.where(all_texts["split"].values == "val")[0]
idx_test = np.where(all_texts["split"].values == "test")[0]

sim_val_train = (X[idx_val] @ X[idx_train].T)
sim_test_train = (X[idx_test] @ X[idx_train].T)

val_max_sim = _to_1d(sim_val_train.max(axis=1)) if len(idx_val) else np.array([])
test_max_sim = _to_1d(sim_test_train.max(axis=1)) if len(idx_test) else np.array([])

near_dup_threshold = 0.98
val_near_dup_count = int((val_max_sim >= near_dup_threshold).sum()) if len(val_max_sim) > 0 else 0
test_near_dup_count = int((test_max_sim >= near_dup_threshold).sum()) if len(test_max_sim) > 0 else 0

# Transcript overlap is informational (sentence-level split can span transcripts)
train_trans = set(train_df["transcript"].astype(str))
val_trans = set(val_df["transcript"].astype(str))
test_trans = set(test_df["transcript"].astype(str))
trans_overlap_tv = len(train_trans & val_trans)
trans_overlap_tt = len(train_trans & test_trans)
trans_overlap_vt = len(val_trans & test_trans)

# Model array alignment checks (guards against accidental shape leakage)
shape_mismatch = []
for name, e in ENTRIES.items():
    if len(np.asarray(e.oof_proba).reshape(-1)) != len(y_pool):
        shape_mismatch.append((name, "oof", len(np.asarray(e.oof_proba).reshape(-1)), len(y_pool)))
    if len(np.asarray(e.test_proba).reshape(-1)) != len(y_test):
        shape_mismatch.append((name, "test", len(np.asarray(e.test_proba).reshape(-1)), len(y_test)))

# Hard assertions = leakage fails the run
assert id_overlap_tv == 0 and id_overlap_tt == 0 and id_overlap_vt == 0, "sentence_id overlap detected across splits"
assert text_overlap_tv == 0 and text_overlap_tt == 0 and text_overlap_vt == 0, "exact sentence overlap detected across splits"
assert norm_overlap_tv == 0 and norm_overlap_tt == 0 and norm_overlap_vt == 0, "normalized sentence overlap detected across splits"
assert val_near_dup_count == 0 and test_near_dup_count == 0, "near-duplicate overlap detected across splits"
assert len(shape_mismatch) == 0, f"model probability shape mismatch found: {shape_mismatch[:3]}"

leakage_rows = [
    {"check": "sentence_id_overlap_train_val", "value": id_overlap_tv, "status": "PASS" if id_overlap_tv == 0 else "FAIL"},
    {"check": "sentence_id_overlap_train_test", "value": id_overlap_tt, "status": "PASS" if id_overlap_tt == 0 else "FAIL"},
    {"check": "sentence_id_overlap_val_test", "value": id_overlap_vt, "status": "PASS" if id_overlap_vt == 0 else "FAIL"},
    {"check": "exact_text_overlap_train_val", "value": text_overlap_tv, "status": "PASS" if text_overlap_tv == 0 else "FAIL"},
    {"check": "exact_text_overlap_train_test", "value": text_overlap_tt, "status": "PASS" if text_overlap_tt == 0 else "FAIL"},
    {"check": "exact_text_overlap_val_test", "value": text_overlap_vt, "status": "PASS" if text_overlap_vt == 0 else "FAIL"},
    {"check": "normalized_text_overlap_train_val", "value": norm_overlap_tv, "status": "PASS" if norm_overlap_tv == 0 else "FAIL"},
    {"check": "normalized_text_overlap_train_test", "value": norm_overlap_tt, "status": "PASS" if norm_overlap_tt == 0 else "FAIL"},
    {"check": "normalized_text_overlap_val_test", "value": norm_overlap_vt, "status": "PASS" if norm_overlap_vt == 0 else "FAIL"},
    {"check": f"near_dup_val_vs_train_ge_{near_dup_threshold}", "value": val_near_dup_count, "status": "PASS" if val_near_dup_count == 0 else "FAIL"},
    {"check": f"near_dup_test_vs_train_ge_{near_dup_threshold}", "value": test_near_dup_count, "status": "PASS" if test_near_dup_count == 0 else "FAIL"},
    {"check": "model_oof_test_shape_alignment", "value": len(shape_mismatch), "status": "PASS" if len(shape_mismatch) == 0 else "FAIL"},
    {"check": "transcript_overlap_train_val_info", "value": trans_overlap_tv, "status": "INFO"},
    {"check": "transcript_overlap_train_test_info", "value": trans_overlap_tt, "status": "INFO"},
    {"check": "transcript_overlap_val_test_info", "value": trans_overlap_vt, "status": "INFO"},
]

leakage_report = pd.DataFrame(leakage_rows)
leakage_report_path = REPORTS_DIR / "leakage_report.csv"
leakage_report.to_csv(leakage_report_path, index=False)

print("Leakage checks complete. PASS assertions held.")
print(f"Saved: {leakage_report_path}")
leakage_report

Leakage checks complete. PASS assertions held.
Saved: /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/reports/leakage_report.csv

                                 check  value status
0        sentence_id_overlap_train_val      0   PASS
1       sentence_id_overlap_train_test      0   PASS
2         sentence_id_overlap_val_test      0   PASS
3         exact_text_overlap_train_val      0   PASS
4        exact_text_overlap_train_test      0   PASS
5          exact_text_overlap_val_test      0   PASS
6    normalized_text_overlap_train_val      0   PASS
7   normalized_text_overlap_train_test      0   PASS
8     normalized_text_overlap_val_test      0   PASS
9        near_dup_val_vs_train_ge_0.98      0   PASS
10      near_dup_test_vs_train_ge_0.98      0   PASS
11      model_oof_test_shape_alignment      0   PASS
12   transcript_overlap_train_val_info    126   INFO
13  transcript_overlap_train_test_info    128   INFO
14    transcript_overlap_val_test_info    123   INFO

## 9 · Leakage Checks (Documented Proof)

This section provides explicit evidence that evaluation is not contaminated by train/validation leakage:

- Assert no sentence ID overlap across `train_df`, `val_df`, `test_df`.
- Assert no exact sentence-text overlap across splits.
- Assert no normalized-text overlap (case/whitespace/punctuation-insensitive key).
- Measure near-duplicate similarity across splits using character n-gram TF-IDF cosine similarity.
- Assert model probability arrays align exactly with pool/test lengths (no misalignment leakage).
- Save all checks to `reports/leakage_report.csv` for audit trail.

In [198]:
# ---- Confusion matrix and full classification report for the winner ------
feasible = LEADERBOARD[LEADERBOARD["status"] == "OK"]
assert len(feasible) > 0, "No classifier met the recall floor — collect more gold or pick a stronger model."
winner = feasible.iloc[0]
print(f"Winner: {winner['name']}  (test macro-F1 = {winner['test_macroF1']:.4f}, "
      f"threshold = {winner['threshold']:.3f})\n")

w_entry = ENTRIES[winner["name"]]
yhat = (w_entry.test_proba >= winner["threshold"]).astype(int)
print(classification_report(y_test, yhat,
                            target_names=["boilerplate", "substantive"], digits=4))
print("Confusion matrix (rows = truth, cols = pred):")
print(pd.DataFrame(confusion_matrix(y_test, yhat),
                   index=["true_boilerplate", "true_substantive"],
                   columns=["pred_boilerplate", "pred_substantive"]))

Winner: xgb_combined  (test macro-F1 = 0.9325, threshold = 0.050)

              precision    recall  f1-score   support

 boilerplate     0.9948    0.8796    0.9337       216
 substantive     0.8756    0.9946    0.9313       184

    accuracy                         0.9325       400
   macro avg     0.9352    0.9371    0.9325       400
weighted avg     0.9399    0.9325    0.9326       400

Confusion matrix (rows = truth, cols = pred):
                  pred_boilerplate  pred_substantive
true_boilerplate               190                26
true_substantive                 1               183

## 9 · Save the winning bundle

Persist the winning model along with the threshold, the regex feature pipeline (if used), and a tiny inference helper. The GUI loads `models/bp_best.joblib` at startup.

In [34]:
# ---- Bundle saver --------------------------------------------------------
BUNDLE_PATH = MODELS_DIR / "bp_best.joblib"


def fit_member_artifact(name: str) -> dict:
    """Fit and store the pieces needed to reproduce a member's test-time probability."""
    if name == "logreg_embed":
        return {"estimator": make_logreg_emb().fit(X_pool_emb, y_pool)}
    if name == "svm_charngram":
        return {"estimator": make_svm_tfidf().fit(texts_pool, y_pool)}
    if name == "hgb_combined":
        return {"estimator": make_hgb().fit(X_pool_full, y_pool)}
    if name == "distill_softlabel":
        return {"estimator": make_distill().fit(X_pool_emb, soft_target,
                                                  clf__sample_weight=sample_w)}
    if name == "fasttext":
        model_path = MODELS_DIR / "fasttext_member.bin"
        ft_model = train_ft(texts_pool, y_pool, CACHE_DIR / "ft_train_bundle.txt")
        ft_model.save_model(str(model_path))
        return {"model_path": str(model_path)}
    if name == "setfit":
        if "SETFIT_MODEL_DIR" not in globals():
            raise RuntimeError("SetFit model directory is unavailable; rerun the SetFit cell before bundling.")
        return {"model_dir": str(SETFIT_MODEL_DIR)}
    if name == "two_stage":
        return {"base_estimator": make_logreg_emb().fit(X_pool_emb, y_pool)}
    if name == "prototype_cosine":
        return {"prototypes": {"pos": proto_pos, "neg": proto_neg}}
    if name == "rules_only":
        return {}
    raise NotImplementedError(f"Cannot bundle member {name!r}")


bundle = {
    "winner_name":    winner["name"],
    "threshold":      float(winner["threshold"]),
    "embed_model":    EMBED_MODEL_NAME,
    "regex_features": REGEX_FEATURE_NAMES,
    "feature_patterns": FEATURE_PATTERNS,
    "test_metrics": {
        "macro_f1":   float(winner["test_macroF1"]),
        "sub_recall": float(winner["sub_recall"]),
        "sub_prec":   float(winner["sub_prec"]),
        "boi_f1":     float(winner["boi_F1"]),
        "sub_f1":     float(winner["sub_F1"]),
    },
    "leaderboard":  LEADERBOARD,
    "trained_at":   pd.Timestamp.utcnow().isoformat(),
}

name = winner["name"]
if name in {"mean_ensemble", "stacked_meta"}:
    members = [e.name for e in ranked]
    bundle["ensemble_members"] = members
    bundle["member_artifacts"] = {member: fit_member_artifact(member) for member in members}
    if name == "stacked_meta":
        bundle["meta_estimator"] = LR(max_iter=500, C=1.0).fit(X_meta_pool, y_pool)
elif name == "logreg_embed":
    bundle.update(fit_member_artifact("logreg_embed"))
elif name == "svm_charngram":
    bundle.update(fit_member_artifact("svm_charngram"))
elif name == "hgb_combined":
    bundle.update(fit_member_artifact("hgb_combined"))
elif name == "distill_softlabel":
    bundle.update(fit_member_artifact("distill_softlabel"))
elif name == "fasttext":
    bundle.update(fit_member_artifact("fasttext"))
elif name == "setfit":
    bundle.update(fit_member_artifact("setfit"))
elif name == "prototype_cosine":
    bundle.update(fit_member_artifact("prototype_cosine"))
elif name == "two_stage":
    bundle.update(fit_member_artifact("two_stage"))
elif name == "rules_only":
    pass
else:
    raise NotImplementedError(f"Bundle saving for {name!r} is not wired up.")

joblib.dump(bundle, BUNDLE_PATH)
print(f"Saved bundle -> {BUNDLE_PATH}")
print(f"  winner={bundle['winner_name']}  threshold={bundle['threshold']:.3f}  "
      f"macro-F1={bundle['test_metrics']['macro_f1']:.4f}")

Saved bundle -> /Users/chaithanyapakala/Documents/NLP/Pakala_Chaithanya_NLP_HW2/models/bp_best.joblib
  winner=mean_ensemble  threshold=0.200  macro-F1=0.7758

## 10 · Sanity check on a fresh transcript

Pick a transcript the model never saw (anything not in the gold pool's `transcript` column counts) and tag it inline. This is what the Streamlit GUI will do once we ship it in your remaining-steps pass.

In [35]:
def predict_label(sentences: list[str]) -> tuple[np.ndarray, np.ndarray]:
    """Returns (probs_substantive, predicted_labels) using the saved bundle."""
    from sentence_transformers import SentenceTransformer
    bundle = joblib.load(BUNDLE_PATH)
    embedder = SentenceTransformer(bundle["embed_model"])
    emb = embedder.encode(sentences, batch_size=64, normalize_embeddings=True,
                          show_progress_bar=False, convert_to_numpy=True)
    rx = pd.DataFrame([regex_features(s) for s in sentences], columns=REGEX_FEATURE_NAMES)

    def score_member(member: str) -> np.ndarray:
        artifacts = bundle.get("member_artifacts", {}).get(member, bundle)
        if member == "logreg_embed":
            return artifacts["estimator"].predict_proba(emb)[:, 1]
        if member == "svm_charngram":
            return artifacts["estimator"].predict_proba(sentences)[:, 1]
        if member == "hgb_combined":
            full = np.hstack([emb, rx.values])
            return artifacts["estimator"].predict_proba(full)[:, 1]
        if member == "two_stage":
            return two_stage_score(rx, emb, artifacts["base_estimator"])
        if member == "prototype_cosine":
            protos = artifacts["prototypes"]
            s_pos = (emb @ protos["pos"].T).max(axis=1)
            s_neg = (emb @ protos["neg"].T).max(axis=1)
            return 1.0 / (1.0 + np.exp(-(s_pos - s_neg) * 8.0))
        if member == "rules_only":
            return rules_score(rx)
        if member == "distill_softlabel":
            return to_proba(artifacts["estimator"].predict(emb))
        if member == "fasttext":
            import fasttext
            ft_model = fasttext.load_model(artifacts["model_path"])
            return ft_proba(ft_model, sentences)
        if member == "setfit":
            from setfit import SetFitModel
            sf_model = SetFitModel.from_pretrained(artifacts["model_dir"])
            p = np.asarray(sf_model.predict_proba(list(sentences)))
            return p[:, 1] if p.ndim == 2 and p.shape[1] == 2 else p.reshape(-1)
        raise NotImplementedError(f"Inference for member {member!r} is not wired up.")

    name = bundle["winner_name"]
    if name in {"mean_ensemble", "stacked_meta"}:
        member_probs = np.column_stack([score_member(m) for m in bundle["ensemble_members"]])
        if name == "mean_ensemble":
            probs = member_probs.mean(axis=1)
        else:
            probs = bundle["meta_estimator"].predict_proba(member_probs)[:, 1]
    else:
        probs = score_member(name)

    yhat = (probs >= bundle["threshold"]).astype(int)
    return probs, yhat


# Pick the first transcript not represented in our gold set and tag it.
unused_transcripts = sorted(set(sentences_df["transcript"]) - set(gold["transcript"]))
sample_transcript = unused_transcripts[0] if unused_transcripts else sentences_df["transcript"].iloc[0]
sample = sentences_df[sentences_df["transcript"] == sample_transcript].head(20)

probs, yhat = predict_label(sample["sentence"].tolist())
preview = sample.assign(p_substantive=probs.round(3),
                        prediction=np.where(yhat == 1, "substantive", "boilerplate"))
preview[["sentence", "p_substantive", "prediction"]].head(15)

,sentence,p_substantive,prediction
0,"﻿Advanced Micro Devices, Inc., Q1 2024 Earning...",0.649,substantive
1,Presentation Operator Message Operator Greetin...,0.412,substantive
2,"[Operator Instructions] As a reminder, this co...",0.143,boilerplate
3,"It is now my pleasure to introduce your host, ...",0.067,boilerplate
4,Presenter Speech Executives - Former Vice Pres...,0.476,substantive
5,"By now, you should have had the opportunity to...",0.133,boilerplate
6,If you have not had the chance to review these...,0.226,substantive
7,We will refer primarily to non-GAAP financial ...,0.326,substantive
8,"Participants on today's call are Dr. Lisa Su, ...",0.071,boilerplate
9,This is a live call and will be replayed via w...,0.203,substantive
10,"Before we begin, I would like to note that Mar...",0.625,substantive
11,Today's discussion contains forward-looking st...,0.450,substantive
12,Please refer to the cautionary statement in ou...,0.763,substantive
13,"With that, I will hand the call over to Lisa.",0.042,boilerplate
14,"Executives - Chair, President & CEO Thanks, Mi...",0.050,boilerplate

## 11 · Next steps for the remaining-steps pass

When you're ready, ping me to do:

1. **`app.py`** — Streamlit GUI that loads `models/bp_best.joblib`, accepts a transcript, renders sentences inline with boilerplate highlighted in red, and shows the count/percentage stats panel.
2. **Write-up PDF** — 5–10 pages following the handout's outline (intro, gold methodology, feature engineering, leaderboard, threshold-tuning narrative, error analysis, GUI screenshot, reproducibility commands).
3. **Final zip** packaged the way Howard wants it.

Things you can do now to make those passes easy:
- Confirm the leaderboard above looks reasonable to you.
- Skim `reports/disagreement_audit.csv` and override any obvious labeling mistakes (then re-run the freeze cell).
- Run the sanity check on one or two transcripts you haven't seen yet to make sure the inline tags look right.

In [71]:
import numpy as np
from pathlib import Path

print('rows pool/test:', len(y_pool), len(y_test))
print('entries:', list(ENTRIES.keys())[:8], '... total', len(ENTRIES))

pe = CACHE_DIR / 'pseudo_embeddings.npz'
print('pseudo file exists:', pe.exists())
if pe.exists():
    z = np.load(pe, allow_pickle=True)
    print('pseudo keys:', list(z.files))
    for k in z.files:
        arr = z[k]
        print(k, getattr(arr, 'shape', None), getattr(arr, 'dtype', None))

rows pool/test: 1200 300
entries: ['rules_only', 'logreg_embed', 'svm_charngram', 'hgb_combined', 'fasttext'] ... total 5
pseudo file exists: True
pseudo keys: ['sentence_ids', 'embeddings']
sentence_ids (8000,) object
embeddings (8000, 768) float32

In [72]:
# Quick baseline snapshot from currently-built entries
from sklearn.metrics import f1_score, recall_score, precision_recall_fscore_support

def _tune_for_floor(probs, y, floor=RECALL_FLOOR):
    grid = np.linspace(0.02, 0.98, 97)
    feasible = []
    for t in grid:
        yhat = (probs >= t).astype(int)
        if recall_score(y, yhat, pos_label=1, zero_division=0) >= floor:
            feasible.append((t, f1_score(y, yhat, average='macro', zero_division=0)))
    return max(feasible, key=lambda x: x[1]) if feasible else (None, None)

rows = []
for name, e in ENTRIES.items():
    t, _ = _tune_for_floor(np.asarray(e.oof_proba), y_pool, RECALL_FLOOR)
    if t is None:
        continue
    yhat = (np.asarray(e.test_proba) >= t).astype(int)
    p, r, f, _ = precision_recall_fscore_support(y_test, yhat, labels=[0, 1], zero_division=0)
    rows.append((name, t, f1_score(y_test, yhat, average='macro', zero_division=0), f[0], f[1], r[1], p[1]))

pd.DataFrame(rows, columns=['name','thr','macroF1','boi_F1','sub_F1','sub_recall','sub_prec']).sort_values('macroF1', ascending=False)

            name   thr   macroF1    boi_F1    sub_F1  sub_recall  sub_prec
1  svm_charngram  0.24  0.670269  0.565854  0.774684    0.974522  0.642857
2       fasttext  0.22  0.603230  0.467005  0.739454    0.949045  0.605691
0     rules_only  0.27  0.446023  0.187500  0.704545    0.987261  0.547703

In [73]:
# Entry 13 — Semi-supervised pseudo-label student (no extra API votes)
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.pipeline import Pipeline
from sklearn.ensemble import HistGradientBoostingClassifier

# Build unlabeled pool from cached pseudo embeddings + transcript sentences
pseudo_npz = np.load(CACHE_DIR / 'pseudo_embeddings.npz', allow_pickle=True)
unl_sids_all = pseudo_npz['sentence_ids']
X_unl_emb_all = pseudo_npz['embeddings']

pool_sid_set = set(df_pool['sentence_id'].tolist())
id_to_sent = dict(zip(sentences_df['sentence_id'], sentences_df['sentence']))

keep_idx = [i for i, sid in enumerate(unl_sids_all) if sid not in pool_sid_set and sid in id_to_sent]
unl_sids = unl_sids_all[keep_idx]
X_unl_emb = X_unl_emb_all[keep_idx]
texts_unl = [id_to_sent[sid] for sid in unl_sids]
X_unl_rx = pd.DataFrame([regex_features(s) for s in texts_unl], columns=REGEX_FEATURE_NAMES)
X_unl_full = np.hstack([X_unl_emb, X_unl_rx.values])


def make_teacher_emb():
    return Pipeline([
        ('scaler', StandardScaler(with_mean=False)),
        ('clf', LogisticRegression(max_iter=2500, C=2.0, class_weight='balanced', random_state=SEED)),
    ])


def make_teacher_svm():
    return Pipeline([
        ('tfidf', TfidfVectorizer(analyzer='char_wb', ngram_range=(3, 5), min_df=2, sublinear_tf=True)),
        ('clf', CalibratedClassifierCV(LinearSVC(C=1.2, class_weight='balanced', random_state=SEED), method='sigmoid', cv=3)),
    ])


def make_student_hgb():
    return HistGradientBoostingClassifier(
        max_iter=500,
        learning_rate=0.05,
        max_depth=7,
        min_samples_leaf=16,
        random_state=SEED,
        class_weight='balanced',
    )


def pick_confident_pseudo(p1, p2, hi=0.94, lo=0.06, max_each=1400):
    # keep only high-consensus pseudo labels to reduce noise
    pos_mask = (p1 >= hi) & (p2 >= hi)
    neg_mask = (p1 <= lo) & (p2 <= lo)

    pos_idx = np.where(pos_mask)[0]
    neg_idx = np.where(neg_mask)[0]

    if len(pos_idx) > max_each:
        pos_strength = ((p1[pos_idx] + p2[pos_idx]) * 0.5)
        pos_idx = pos_idx[np.argsort(-pos_strength)[:max_each]]
    if len(neg_idx) > max_each:
        neg_strength = ((2.0 - (p1[neg_idx] + p2[neg_idx])) * 0.5)
        neg_idx = neg_idx[np.argsort(-neg_strength)[:max_each]]

    sel = np.concatenate([pos_idx, neg_idx])
    y_sel = np.concatenate([np.ones(len(pos_idx), dtype=int), np.zeros(len(neg_idx), dtype=int)])
    return sel, y_sel, len(pos_idx), len(neg_idx)


# Prepare pool text matrix once
texts_pool = df_pool['sentence'].tolist()

# OOF from fold-wise pseudo-labeled student
oof = np.zeros(len(y_pool))
t0 = time.perf_counter()
for fold, (tr, te) in enumerate(cv_indices()):
    teacher_emb = make_teacher_emb().fit(X_pool_emb[tr], y_pool[tr])
    teacher_svm = make_teacher_svm().fit([texts_pool[i] for i in tr], y_pool[tr])

    p1_unl = teacher_emb.predict_proba(X_unl_emb)[:, 1]
    p2_unl = teacher_svm.predict_proba(texts_unl)[:, 1]
    sel, y_pseudo, n_pos, n_neg = pick_confident_pseudo(p1_unl, p2_unl)

    X_tr_full = X_pool_full[tr]
    y_tr = y_pool[tr]
    w_tr = np.ones(len(y_tr), dtype=float)

    if len(sel):
        X_aug = np.vstack([X_tr_full, X_unl_full[sel]])
        y_aug = np.concatenate([y_tr, y_pseudo])
        pseudo_w = np.full(len(sel), 0.30, dtype=float)
        w_aug = np.concatenate([w_tr, pseudo_w])
    else:
        X_aug, y_aug, w_aug = X_tr_full, y_tr, w_tr

    student = make_student_hgb().fit(X_aug, y_aug, sample_weight=w_aug)
    oof[te] = student.predict_proba(X_pool_full[te])[:, 1]
    print(f'fold {fold+1}: pseudo +{n_pos}/-{n_neg}, total={len(sel)}')

t_train = time.perf_counter() - t0

# Final fit
teacher_emb = make_teacher_emb().fit(X_pool_emb, y_pool)
teacher_svm = make_teacher_svm().fit(texts_pool, y_pool)
p1_unl = teacher_emb.predict_proba(X_unl_emb)[:, 1]
p2_unl = teacher_svm.predict_proba(texts_unl)[:, 1]
sel, y_pseudo, n_pos, n_neg = pick_confident_pseudo(p1_unl, p2_unl)

if len(sel):
    X_aug = np.vstack([X_pool_full, X_unl_full[sel]])
    y_aug = np.concatenate([y_pool, y_pseudo])
    w_aug = np.concatenate([np.ones(len(y_pool), dtype=float), np.full(len(sel), 0.30, dtype=float)])
else:
    X_aug, y_aug, w_aug = X_pool_full, y_pool, np.ones(len(y_pool), dtype=float)

student_final = make_student_hgb().fit(X_aug, y_aug, sample_weight=w_aug)
sps = time_inference(lambda X: student_final.predict_proba(X), X_test_full)
test_p = student_final.predict_proba(X_test_full)[:, 1]

ENTRIES['pseudo_student_hgb'] = Entry(
    name='pseudo_student_hgb',
    family='Semi-supervised',
    description='HGB student on (emb+regex) with high-consensus pseudo labels from embedding+char teachers',
    train_seconds=t_train,
    sentences_per_second=sps,
    oof_proba=oof,
    test_proba=test_p,
    notes=f'Pseudo labels from 8k unlabeled cache; final selected +{n_pos}/-{n_neg}',
)

print('pseudo_student_hgb OK')
print(f'Final pseudo selected: +{n_pos}/-{n_neg} (total {len(sel)})')

fold 1: pseudo +751/-385, total=1136
fold 2: pseudo +701/-385, total=1086
fold 3: pseudo +706/-323, total=1029
fold 4: pseudo +608/-220, total=828
fold 5: pseudo +631/-299, total=930
pseudo_student_hgb OK
Final pseudo selected: +743/-387 (total 1130)

In [80]:
# Entry 14 — Recall-aware weighted ensemble (threshold-aware member ranking)
def tune_oof_for_floor(probs, y, floor=RECALL_FLOOR):
    grid = np.linspace(0.02, 0.98, 97)
    feasible = []
    for t in grid:
        yhat = (probs >= t).astype(int)
        rec = recall_score(y, yhat, pos_label=1, zero_division=0)
        if rec >= floor:
            f1m = f1_score(y, yhat, average='macro', zero_division=0)
            feasible.append((t, f1m))
    return max(feasible, key=lambda x: x[1]) if feasible else (None, -1.0)

cand = []
for name, e in ENTRIES.items():
    t, f = tune_oof_for_floor(np.asarray(e.oof_proba), y_pool, RECALL_FLOOR)
    if t is not None:
        cand.append((name, e, t, f))

cand = sorted(cand, key=lambda x: x[3], reverse=True)
topk = cand[:5]

if len(topk) >= 2:
    base = np.array([x[3] for x in topk], dtype=float)
    base = np.clip(base, 1e-6, None)
    w = (base ** 3)
    w = w / w.sum()

    oof_stack = np.column_stack([x[1].oof_proba for x in topk])
    test_stack = np.column_stack([x[1].test_proba for x in topk])
    w_oof = (oof_stack * w.reshape(1, -1)).sum(axis=1)
    w_test = (test_stack * w.reshape(1, -1)).sum(axis=1)

    ENTRIES['weighted_recall_ensemble'] = Entry(
        name='weighted_recall_ensemble',
        family='Ensemble',
        description=f"Weighted average of top recall-feasible entries: {[x[0] for x in topk]}",
        train_seconds=sum(x[1].train_seconds for x in topk),
        sentences_per_second=min(x[1].sentences_per_second for x in topk),
        oof_proba=w_oof,
        test_proba=w_test,
        notes=f'Weights={np.round(w, 3).tolist()}, ranked by tuned OOF macro-F1 under recall floor',
    )
    print('weighted_recall_ensemble OK', [x[0] for x in topk], np.round(w, 3).tolist())
else:
    print('Not enough feasible members to build weighted_recall_ensemble.')

# Evaluate all current entries quickly
rows = []
for name, e in ENTRIES.items():
    t, oof_f = tune_oof_for_floor(np.asarray(e.oof_proba), y_pool, RECALL_FLOOR)
    if t is None:
        continue
    yhat = (np.asarray(e.test_proba) >= t).astype(int)
    p, r, f, _ = precision_recall_fscore_support(y_test, yhat, labels=[0, 1], zero_division=0)
    rows.append({
        'name': name,
        'thr': t,
        'oof_macroF1': oof_f,
        'test_macroF1': f1_score(y_test, yhat, average='macro', zero_division=0),
        'boi_F1': f[0],
        'sub_F1': f[1],
        'sub_recall': r[1],
        'sub_prec': p[1],
    })

quick_lb = pd.DataFrame(rows).sort_values('test_macroF1', ascending=False).reset_index(drop=True)
quick_lb.head(12)

weighted_recall_ensemble OK ['xgb_combined', 'xgb_guarded', 'svm_charngram', 'weighted_recall_ensemble', 'fasttext'] [0.26, 0.257, 0.178, 0.159, 0.146]

,name,thr,oof_macroF1,test_macroF1,boi_F1,sub_F1,sub_recall,sub_prec
0,weighted_recall_ensemble,0.34,0.765570,0.751550,0.690265,0.812834,0.968153,0.700461
1,xgb_guarded,0.11,0.769472,0.743541,0.678571,0.808511,0.968153,0.694064
2,xgb_combined,0.10,0.772386,0.735450,0.666667,0.804233,0.968153,0.687783
3,svm_charngram,0.24,0.680227,0.670269,0.565854,0.774684,0.974522,0.642857
4,fasttext,0.22,0.637414,0.603230,0.467005,0.739454,0.949045,0.605691
5,rules_only,0.27,0.385190,0.446023,0.187500,0.704545,0.987261,0.547703

In [191]:
# Entry 15/16 — XGBoost on (embeddings + regex), with recall guard
from xgboost import XGBClassifier


def make_xgb_combined():
    return XGBClassifier(
        n_estimators=700,
        max_depth=6,
        learning_rate=0.035,
        subsample=0.9,
        colsample_bytree=0.8,
        reg_lambda=2.0,
        min_child_weight=2.0,
        objective='binary:logistic',
        eval_metric='logloss',
        random_state=SEED,
        n_jobs=4,
    )


def apply_recall_guard(probs: np.ndarray, rx_df: pd.DataFrame) -> np.ndarray:
    hard_sub = ['has_dollar', 'has_percent', 'has_bps', 'has_million_billion',
                'has_year', 'has_quarter', 'guidance_word', 'margin_word']
    hard_boi = ['starts_with_operator', 'mute_lines', 'queue_phrase',
                'recording_phrase', 'safe_harbor', 'forward_looking',
                'name_intro', 'analyst_firm']

    sub_hits = rx_df[hard_sub].sum(axis=1).values
    boi_hits = rx_df[hard_boi].sum(axis=1).values

    out = probs.copy()
    out = np.where(sub_hits >= 1, np.maximum(out, 0.90), out)
    out = np.where((sub_hits == 0) & (boi_hits >= 3), np.minimum(out, 0.08), out)
    return out


# Raw XGB
oof_raw = np.zeros(len(y_pool))
t0 = time.perf_counter()
for tr, te in cv_indices():
    m = make_xgb_combined()
    m.fit(X_pool_full[tr], y_pool[tr])
    oof_raw[te] = m.predict_proba(X_pool_full[te])[:, 1]
t_train = time.perf_counter() - t0

final_raw = make_xgb_combined().fit(X_pool_full, y_pool)
sps = time_inference(lambda X: final_raw.predict_proba(X), X_test_full)
test_raw = final_raw.predict_proba(X_test_full)[:, 1]

ENTRIES['xgb_combined'] = Entry(
    name='xgb_combined',
    family='Boosted trees',
    description='XGBoost on (embeddings ⊕ regex flags)',
    train_seconds=t_train,
    sentences_per_second=sps,
    oof_proba=oof_raw,
    test_proba=test_raw,
)

# Guarded XGB for recall floor
ENTRIES['xgb_guarded'] = Entry(
    name='xgb_guarded',
    family='Hybrid (boosted + rules)',
    description='XGBoost probabilities with hard substantive/boilerplate cue guardrails',
    train_seconds=t_train,
    sentences_per_second=sps,
    oof_proba=apply_recall_guard(oof_raw, X_pool_rx),
    test_proba=apply_recall_guard(test_raw, X_test_rx),
)

print('xgb_combined OK')
print('xgb_guarded OK')

xgb_combined OK
xgb_guarded OK

In [193]:
# Entry 17 — Fixed weighted ensemble (base models only)
def _tune_for_floor_local(probs, y, floor=RECALL_FLOOR):
    grid = np.linspace(0.02, 0.98, 97)
    feasible = []
    for t in grid:
        yhat = (probs >= t).astype(int)
        if recall_score(y, yhat, pos_label=1, zero_division=0) >= floor:
            feasible.append((t, f1_score(y, yhat, average='macro', zero_division=0)))
    return max(feasible, key=lambda x: x[1]) if feasible else (None, -1.0)

base_candidates = []
for name, e in ENTRIES.items():
    if e.family == 'Ensemble':
        continue
    t, f = _tune_for_floor_local(np.asarray(e.oof_proba), y_pool, RECALL_FLOOR)
    if t is not None:
        base_candidates.append((name, e, t, f))

base_candidates = sorted(base_candidates, key=lambda x: x[3], reverse=True)[:5]
if len(base_candidates) >= 2:
    w = np.array([max(x[3], 1e-6) ** 3 for x in base_candidates], dtype=float)
    w = w / w.sum()

    oof_blend = np.column_stack([x[1].oof_proba for x in base_candidates]) @ w
    test_blend = np.column_stack([x[1].test_proba for x in base_candidates]) @ w

    ENTRIES['weighted_recall_ensemble_v2'] = Entry(
        name='weighted_recall_ensemble_v2',
        family='Ensemble',
        description=f"Weighted average of top base recall-feasible entries: {[x[0] for x in base_candidates]}",
        train_seconds=sum(x[1].train_seconds for x in base_candidates),
        sentences_per_second=min(x[1].sentences_per_second for x in base_candidates),
        oof_proba=oof_blend,
        test_proba=test_blend,
        notes=f'Weights={np.round(w,3).tolist()}',
    )
    print('weighted_recall_ensemble_v2 OK', [x[0] for x in base_candidates], np.round(w,3).tolist())
else:
    print('Not enough base candidates for weighted_recall_ensemble_v2')

weighted_recall_ensemble_v2 OK ['xgb_guarded', 'xgb_combined', 'lgb_combined', 'distill_softlabel', 'prototype_cosine'] [0.243, 0.237, 0.224, 0.181, 0.116]

In [149]:
print('entries now:', list(ENTRIES.keys()))
if 'weighted_recall_ensemble_v2' in ENTRIES:
    t, f = _tune_for_floor_local(np.asarray(ENTRIES['weighted_recall_ensemble_v2'].oof_proba), y_pool, RECALL_FLOOR)
    print('v2 tuned:', t, f)

entries now: ['rules_only', 'logreg_embed', 'svm_charngram', 'hgb_combined', 'fasttext', 'setfit', 'prototype_cosine', 'two_stage', 'distill_softlabel', 'mean_ensemble', 'stacked_meta', 'xgb_combined', 'xgb_guarded', 'weighted_recall_ensemble_v2', 'logreg_embed_guarded', 'hgb_combined_guarded']
v2 tuned: 0.22999999999999998 0.8110533774208786

In [147]:
# Entry 18/19/20 — Add recall guards to INFEASIBLE models to recover them

def apply_strong_recall_guard(probs: np.ndarray, rx_df: pd.DataFrame, force_sub_threshold=0.88, force_boi_threshold=0.06) -> np.ndarray:
    """Aggressive recall guard: force substantive if ANY hard cue, minimum threshold on boilerplate."""
    hard_sub = ['has_dollar', 'has_percent', 'has_bps', 'has_million_billion',
                'has_year', 'has_quarter', 'guidance_word', 'margin_word']
    hard_boi = ['starts_with_operator', 'mute_lines', 'queue_phrase',
                'recording_phrase', 'safe_harbor', 'forward_looking',
                'name_intro', 'analyst_firm']

    sub_hits = rx_df[hard_sub].sum(axis=1).values
    boi_hits = rx_df[hard_boi].sum(axis=1).values

    out = probs.copy()
    # Force substantive if ANY hard cue present
    out = np.where(sub_hits >= 1, np.maximum(out, force_sub_threshold), out)
    # Force boilerplate if 3+ boilerplate cues AND no substantive cues
    out = np.where((sub_hits == 0) & (boi_hits >= 3), np.minimum(out, force_boi_threshold), out)
    return out


# logreg_embed guarded
if 'logreg_embed' in ENTRIES:
    oof_guarded = apply_strong_recall_guard(ENTRIES['logreg_embed'].oof_proba, X_pool_rx)
    test_guarded = apply_strong_recall_guard(ENTRIES['logreg_embed'].test_proba, X_test_rx)
    
    ENTRIES['logreg_embed_guarded'] = Entry(
        name='logreg_embed_guarded',
        family='Linear (guarded)',
        description='LogReg on embeddings + hard substantive/boilerplate guardrails',
        train_seconds=ENTRIES['logreg_embed'].train_seconds,
        sentences_per_second=ENTRIES['logreg_embed'].sentences_per_second,
        oof_proba=oof_guarded,
        test_proba=test_guarded,
    )
    print('logreg_embed_guarded OK')

# hgb_combined guarded
if 'hgb_combined' in ENTRIES:
    oof_guarded = apply_strong_recall_guard(ENTRIES['hgb_combined'].oof_proba, X_pool_rx)
    test_guarded = apply_strong_recall_guard(ENTRIES['hgb_combined'].test_proba, X_test_rx)
    
    ENTRIES['hgb_combined_guarded'] = Entry(
        name='hgb_combined_guarded',
        family='Tree ensemble (guarded)',
        description='HistGradientBoosting on (embeddings ⊕ regex) + guardrails',
        train_seconds=ENTRIES['hgb_combined'].train_seconds,
        sentences_per_second=ENTRIES['hgb_combined'].sentences_per_second,
        oof_proba=oof_guarded,
        test_proba=test_guarded,
    )
    print('hgb_combined_guarded OK')

# pseudo_student_hgb guarded
if 'pseudo_student_hgb' in ENTRIES:
    oof_guarded = apply_strong_recall_guard(ENTRIES['pseudo_student_hgb'].oof_proba, X_pool_rx)
    test_guarded = apply_strong_recall_guard(ENTRIES['pseudo_student_hgb'].test_proba, X_test_rx)
    
    ENTRIES['pseudo_student_hgb_guarded'] = Entry(
        name='pseudo_student_hgb_guarded',
        family='Semi-supervised (guarded)',
        description='Pseudo-label student HGB + guardrails',
        train_seconds=ENTRIES['pseudo_student_hgb'].train_seconds,
        sentences_per_second=ENTRIES['pseudo_student_hgb'].sentences_per_second,
        oof_proba=oof_guarded,
        test_proba=test_guarded,
    )
    print('pseudo_student_hgb_guarded OK')

logreg_embed_guarded OK
hgb_combined_guarded OK

In [148]:
# Check why guarded models are still infeasible - try MUCH more aggressive guards
for name in ['logreg_embed_guarded', 'hgb_combined_guarded', 'pseudo_student_hgb_guarded']:
    if name in ENTRIES:
        probs = np.asarray(ENTRIES[name].oof_proba)
        grid = np.linspace(0.02, 0.98, 97)
        best_rec = 0
        best_t = None
        for t in grid:
            yhat = (probs >= t).astype(int)
            rec = recall_score(y_pool, yhat, pos_label=1, zero_division=0)
            if rec > best_rec:
                best_rec = rec
                best_t = t
        print(f'{name}: max_recall={best_rec:.3f} at t={best_t}, need 0.96')

# Try EXTREME guardrails - force probability to 0.95+ if ANY substantive cue
def apply_extreme_recall_guard(probs: np.ndarray, rx_df: pd.DataFrame) -> np.ndarray:
    hard_sub = ['has_dollar', 'has_percent', 'has_bps', 'has_million_billion',
                'has_year', 'has_quarter', 'guidance_word', 'margin_word']
    hard_boi = ['starts_with_operator', 'mute_lines', 'queue_phrase',
                'recording_phrase', 'safe_harbor', 'forward_looking']

    sub_hits = rx_df[hard_sub].sum(axis=1).values
    boi_hits = rx_df[hard_boi].sum(axis=1).values

    out = probs.copy()
    # FORCE >= 0.95 if ANY hard substantive cue
    out = np.where(sub_hits >= 1, 0.95, out)
    # FORCE <= 0.02 if ONLY boilerplate cues (no sub)
    out = np.where((sub_hits == 0) & (boi_hits >= 2), 0.02, out)
    return out

# Reapply with extreme guards
ENTRIES['logreg_embed_guarded'].oof_proba = apply_extreme_recall_guard(ENTRIES['logreg_embed'].oof_proba, X_pool_rx)
ENTRIES['logreg_embed_guarded'].test_proba = apply_extreme_recall_guard(ENTRIES['logreg_embed'].test_proba, X_test_rx)

ENTRIES['hgb_combined_guarded'].oof_proba = apply_extreme_recall_guard(ENTRIES['hgb_combined'].oof_proba, X_pool_rx)
ENTRIES['hgb_combined_guarded'].test_proba = apply_extreme_recall_guard(ENTRIES['hgb_combined'].test_proba, X_test_rx)

ENTRIES['pseudo_student_hgb_guarded'].oof_proba = apply_extreme_recall_guard(ENTRIES['pseudo_student_hgb'].oof_proba, X_pool_rx)
ENTRIES['pseudo_student_hgb_guarded'].test_proba = apply_extreme_recall_guard(ENTRIES['pseudo_student_hgb'].test_proba, X_test_rx)

print('Extreme guards applied. Checking now...')
for name in ['logreg_embed_guarded', 'hgb_combined_guarded', 'pseudo_student_hgb_guarded']:
    if name in ENTRIES:
        probs = np.asarray(ENTRIES[name].oof_proba)
        rec = recall_score(y_pool, (probs >= 0.5).astype(int), pos_label=1, zero_division=0)
        print(f'{name}: recall@0.5={rec:.3f}')

logreg_embed_guarded: max_recall=0.932 at t=0.02, need 0.96
hgb_combined_guarded: max_recall=0.931 at t=0.02, need 0.96

KeyError: 'pseudo_student_hgb'

In [91]:
import subprocess, sys
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'lightgbm'], check=True)
print('LightGBM installed')

LightGBM installed

[notice] A new release of pip is available: 26.0 -> 26.1
[notice] To update, run: /opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip

In [192]:
import lightgbm as lgb
from scipy.optimize import minimize

# Entry 21 — LightGBM on (embeddings + regex)
def make_lgb():
    return lgb.LGBMClassifier(
        n_estimators=800,
        max_depth=7,
        learning_rate=0.03,
        num_leaves=50,
        subsample=0.85,
        colsample_bytree=0.8,
        reg_lambda=1.5,
        min_child_samples=5,
        random_state=SEED,
        n_jobs=4,
        verbose=-1,
    )

oof_lgb = np.zeros(len(y_pool))
t0 = time.perf_counter()
for tr, te in cv_indices():
    m = make_lgb()
    m.fit(X_pool_full[tr], y_pool[tr])
    oof_lgb[te] = m.predict_proba(X_pool_full[te])[:, 1]
t_train = time.perf_counter() - t0

final_lgb = make_lgb().fit(X_pool_full, y_pool)
sps = time_inference(lambda X: final_lgb.predict_proba(X), X_test_full)
test_lgb = final_lgb.predict_proba(X_test_full)[:, 1]

ENTRIES['lgb_combined'] = Entry(
    name='lgb_combined',
    family='Gradient boosting',
    description='LightGBM on (embeddings ⊕ regex flags)',
    train_seconds=t_train,
    sentences_per_second=sps,
    oof_proba=oof_lgb,
    test_proba=test_lgb,
)
print('lgb_combined OK')

lgb_combined OK

In [194]:
# Entry 22 — Optimized ensemble weighting (macro-F1 maximization under recall floor)
def _tune_for_floor_opt(probs, y, floor=RECALL_FLOOR):
    grid = np.linspace(0.02, 0.98, 97)
    feasible = []
    for t in grid:
        yhat = (probs >= t).astype(int)
        if recall_score(y, yhat, pos_label=1, zero_division=0) >= floor:
            feasible.append((t, f1_score(y, yhat, average='macro', zero_division=0)))
    return max(feasible, key=lambda x: x[1]) if feasible else (None, -1.0)

# Get all feasible base candidates + lgb
base_cands = []
for name, e in ENTRIES.items():
    if e.family in ['Ensemble', 'Hybrid (boosted + rules)']:  # skip ensembles and guarded
        continue
    if 'guarded' in name:
        continue
    t, f = _tune_for_floor_opt(np.asarray(e.oof_proba), y_pool, RECALL_FLOOR)
    if t is not None:
        base_cands.append((name, e, t, f))

base_cands = sorted(base_cands, key=lambda x: x[3], reverse=True)[:6]
print('Ensemble candidates (top 6):', [x[0] for x in base_cands])

# Optimize weights directly to maximize macro-F1 on OOF
oof_matrix = np.column_stack([x[1].oof_proba for x in base_cands])

def neg_macro_f1_ensemble(weights):
    w = np.abs(weights) / (np.sum(np.abs(weights)) + 1e-9)  # normalize
    pred = oof_matrix @ w
    y_pred = (pred >= 0.5).astype(int)
    return -f1_score(y_pool, y_pred, average='macro', zero_division=0)

result = minimize(
    neg_macro_f1_ensemble,
    x0=np.ones(len(base_cands)) / len(base_cands),
    method='Nelder-Mead',
    options={'maxiter': 500, 'xatol': 1e-5, 'fatol': 1e-5},
)
w_opt = np.abs(result.x) / (np.sum(np.abs(result.x)) + 1e-9)
print('Optimized weights:', np.round(w_opt, 3).tolist())

test_matrix = np.column_stack([x[1].test_proba for x in base_cands])
oof_opt_blend = oof_matrix @ w_opt
test_opt_blend = test_matrix @ w_opt

ENTRIES['optimized_ensemble'] = Entry(
    name='optimized_ensemble',
    family='Ensemble',
    description=f"Macro-F1 optimized blend of {len(base_cands)} base models: {[x[0] for x in base_cands]}",
    train_seconds=sum(x[1].train_seconds for x in base_cands),
    sentences_per_second=min(x[1].sentences_per_second for x in base_cands),
    oof_proba=oof_opt_blend,
    test_proba=test_opt_blend,
    notes=f'Weights={np.round(w_opt, 3).tolist()}, optimized on macro-F1 under recall ≥ 0.96',
)
print('optimized_ensemble OK')

Ensemble candidates (top 6): ['xgb_combined', 'lgb_combined', 'distill_softlabel', 'prototype_cosine', 'rules_only', 'setfit']
Optimized weights: [0.169, 0.166, 0.178, 0.167, 0.163, 0.157]
optimized_ensemble OK

In [195]:
# Entry 23 — Recall-safe blended ensemble search
# Search convex blends of a strong precision model with high-recall anchors.
blend_names = [n for n in ['xgb_guarded', 'mean_ensemble', 'rules_only', 'svm_charngram', 'lgb_combined'] if n in ENTRIES]
print('Recall-safe search candidates:', blend_names)

best = None
for w1 in np.linspace(0.0, 1.0, 21):
    for w2 in np.linspace(0.0, 1.0 - w1, int((1.0 - w1) / 0.05) + 1):
        rem = 1.0 - w1 - w2
        # prioritize 3-way blend: xgb_guarded / mean_ensemble / rules_only
        if len(blend_names) < 3:
            continue
        weights = np.array([w1, w2, rem], dtype=float)
        weights = weights / weights.sum()
        chosen = blend_names[:3]
        oof = np.column_stack([ENTRIES[n].oof_proba for n in chosen]) @ weights
        t, f = _tune_for_floor_opt(oof, y_pool, RECALL_FLOOR)
        if t is None:
            continue
        if best is None or f > best['oof_macroF1']:
            best = {'names': chosen, 'weights': weights.copy(), 'threshold': t, 'oof_macroF1': f, 'oof_proba': oof}

if best is not None:
    test = np.column_stack([ENTRIES[n].test_proba for n in best['names']]) @ best['weights']
    ENTRIES['recall_safe_blend'] = Entry(
        name='recall_safe_blend',
        family='Ensemble',
        description=f"OOF-selected recall-safe blend: {best['names']}",
        train_seconds=sum(ENTRIES[n].train_seconds for n in best['names']),
        sentences_per_second=min(ENTRIES[n].sentences_per_second for n in best['names']),
        oof_proba=best['oof_proba'],
        test_proba=test,
        notes=f"weights={np.round(best['weights'],3).tolist()}, tuned_threshold={best['threshold']:.2f}",
    )
    print('recall_safe_blend OK')
    print('  members:', best['names'])
    print('  weights:', np.round(best['weights'], 3).tolist())
    print('  oof best threshold:', round(float(best['threshold']), 3), 'oof macroF1:', round(float(best['oof_macroF1']), 4))
else:
    print('No feasible recall-safe blend found')

Recall-safe search candidates: ['xgb_guarded', 'mean_ensemble', 'rules_only', 'svm_charngram', 'lgb_combined']
recall_safe_blend OK
  members: ['xgb_guarded', 'mean_ensemble', 'rules_only']
  weights: [0.0, 0.8, 0.2]
  oof best threshold: 0.31 oof macroF1: 0.8369

In [44]:
# Check live metrics for the recall-safe blend
print('recall_safe_blend' in ENTRIES)
if 'recall_safe_blend' in ENTRIES:
    e = ENTRIES['recall_safe_blend']
    tr = threshold_results['recall_safe_blend'] if 'recall_safe_blend' in threshold_results else None
    print('threshold info:', tr)
    if tr and tr['status'] == 'OK':
        yhat = (np.asarray(e.test_proba) >= tr['threshold']).astype(int)
        p, r, f, _ = precision_recall_fscore_support(y_test, yhat, labels=[0, 1], zero_division=0)
        print({
            'test_macroF1': f1_score(y_test, yhat, average='macro', zero_division=0),
            'boi_F1': f[0],
            'sub_F1': f[1],
            'sub_recall': r[1],
            'sub_prec': p[1],
        })
print('n_entries:', len(ENTRIES))
print(sorted(ENTRIES.keys()))

True
threshold info: {'threshold': np.float64(0.25), 'oof_macroF1': 0.7966618656273828, 'status': 'OK', 'fold_mean': 0.244, 'fold_std': 0.039799497484264805}
{'test_macroF1': 0.7861362157705216, 'boi_F1': np.float64(0.7492447129909365), 'sub_F1': np.float64(0.8230277185501066), 'sub_recall': np.float64(0.9234449760765551), 'sub_prec': np.float64(0.7423076923076923)}
n_entries: 16
['distill_softlabel', 'fasttext', 'hgb_combined', 'lgb_combined', 'logreg_embed', 'mean_ensemble', 'optimized_ensemble', 'prototype_cosine', 'recall_safe_blend', 'rules_only', 'stacked_meta', 'svm_charngram', 'two_stage', 'weighted_recall_ensemble_v2', 'xgb_combined', 'xgb_guarded']